<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_akun_ortu extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata($nis)
    {
        $this->db->select('*');
        $this->db->from('tb_akun_ortu');
        $this->db->join('tb_santri', 'nis_lokal = id_ortu','right');
        $this->db->where('tb_santri.nis_lokal',$nis);
        $this->db->where('tb_akun_ortu.jenis_akun','santri');
        return $this->db->get();
    }

    function periksaakun($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_akun_ortu');
      $this->db->join('tb_santri', 'nis_lokal = id_ortu','right');
      $this->db->where('tb_santri.nis_lokal',$nis);
      $this->db->where('tb_akun_ortu.jenis_akun','santri');
      return $this->db->get()->num_rows();
    }

    function lihatdatap($nis)
    {
        $this->db->select('*');
        $this->db->from('tb_akun_ortu');
        $this->db->join('tb_santriwati', 'nis_lokal = id_ortu','right');
        $this->db->where('tb_santriwati.nis_lokal',$nis);
        $this->db->where('tb_akun_ortu.jenis_akun','santriwati');
        return $this->db->get();
    }

    function periksaakunp($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_akun_ortu');
      $this->db->join('tb_santriwati', 'nis_lokal = id_ortu','right');
      $this->db->where('tb_santriwati.nis_lokal',$nis);
      $this->db->where('tb_akun_ortu.jenis_akun','santriwati');
      return $this->db->get()->num_rows();
    }

    // function lihatdatasatu($nama_akun)
    // {
    //     $this->db->select('nip_staff_admin, nama_akun, kata_sandi, kode_role_admin, nama_role, nama_lengkap');
    //     $this->db->from('tb_akun_admin');
    //     $this->db->join('tb_role_admin', 'kode_role_admin = kode_role');
    //     $this->db->join('tb_staff', 'nip_staff_admin = nip_staff');
    //     $this->db->where("nama_akun",$nama_akun);
    //     return $this->db->get();
    // }
    //
    // function cekdata($nama_akun)
    // {
    //     $this->db->where("nama_akun",$nama_akun);
    //     return $this->db->get('tb_akun_admin')->num_rows();
    // }
    //
    // function cekdataedit($nama_akun)
    // {
    //     $query = $this->db->where(['nama_akun'=>$nama_akun])
    //                       ->get('tb_akun_admin');
    //     if($query->num_rows() > 0){
    //       return $query->row();
    //     }
    // }

    function tambahjenisakun()
    {
        return $this->db->query('UPDATE tb_akun_ortu RIGHT JOIN tb_santri ON nis_lokal = id_ortu
                          SET jenis_akun = IF(jenis_kelamin = "L", "santri", IF(jenis_kelamin = "P", "santriwati", jenis_akun))
                          WHERE jenis_akun = ""');
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_akun_ortu',$array);
    }


    function editdata($id,$jenis,$array)
    {
        $this->db->where("id_ortu",$id);
        $this->db->where("jenis_akun",$jenis);
        return $this->db->update('tb_akun_ortu',$array);
    }


    function hapus($nama_akun)
    {
        $this->db->where("nama_akun",$nama_akun);
        return $this->db->delete('tb_akun_admin');
    }
    function ambilroleadmin(){
        $this->db->order_by("nama_role","ASC");
        return $this->db->get('tb_role_admin');
    }
    function ambilstaff(){
        $this->db->order_by("nama_lengkap","ASC");
        return $this->db->get('tb_staff');
    }
}
