<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_alat_transportasi extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        return $this->db->get('tb_alat_transportasi');
    }

    function lihatdatasatu($id_alat_transportasi)
    {
        $this->db->where("id_alat_transportasi",$id_alat_transportasi);
        return $this->db->get('tb_alat_transportasi');
    }

    function cekdata($id_alat_transportasi)
    {
        $this->db->where("id_alat_transportasi",$id_alat_transportasi);
        return $this->db->get('tb_alat_transportasi')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_alat_transportasi',$array);
    }

    function editdata($id_alat_transportasi,$array)
    {
        $this->db->where("id_alat_transportasi",$id_alat_transportasi);
        return $this->db->update('tb_alat_transportasi',$array);
    }
    function hapus($id_alat_transportasi)
    {
        $this->db->where("id_alat_transportasi",$id_alat_transportasi);
        return $this->db->delete('tb_alat_transportasi');
    }
}
