<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_guru extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get tb_role_admin by kode_role
     */
    function lihatdata()
    {
        return $this->db->get('tb_guru');
    }

    function lihatdatasatu($nip)
    {
        $this->db->where("nip_guru",$nip);
        return $this->db->get('tb_guru');
    }

    function cekdata($nip)
    {
        $this->db->where("nip_guru",$nip);
        return $this->db->get('tb_guru')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_guru',$array);
    }

    function editdata($nip,$array)
    {
        $this->db->where("nip_guru",$nip);
        return $this->db->update('tb_guru',$array);
    }
    function hapus($nip)
    {
        $this->db->where("nip_guru",$nip);
        return $this->db->delete('tb_guru');
    }
   /////////////////////////////////////////

   function lihatdataberkas($nip)
   {
        $this->db->where("nip_guru",$nip);
        return $this->db->get('tb_berkas_guru');
   }

   function tambahdataberkas($array)
   {
       return $this->db->insert('tb_berkas_guru',$array);
   }

   function lihatdatasatuberkas($id_berkas)
   {
       $this->db->where("id_berkas",$id_berkas);
       return $this->db->get('tb_berkas_guru');
   }

   function cekdataberkas($id_berkas)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->get('tb_berkas_guru')->num_rows();
    }

    function editdataaberkas($id_berkas,$array)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->update('tb_berkas_guru',$array);
    }
    function hapusberkas($id_berkas)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->delete('tb_berkas_guru');
    }

}
