<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_infaq extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata($tahun,$bulan)
    {
        $this->db->select('*');
        $this->db->from('tb_pembayaran_spp');
        $this->db->join('tb_santri', 'tb_pembayaran_spp.nis_santri = tb_santri.nis_lokal');
        $this->db->where('tb_pembayaran_spp.spp_tahun', $tahun);
        $this->db->where('tb_pembayaran_spp.spp_bulan', $bulan);
        return $this->db->get();
    }

    function detilinfaq($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_pembayaran_spp');
      $this->db->join('tb_santri', 'tb_pembayaran_spp.nis_santri = tb_santri.nis_lokal');
      $this->db->where('tb_pembayaran_spp.nis_santri', $nis);
      $this->db->order_by("tb_pembayaran_spp.spp_tahun", "desc");
      $this->db->order_by("tb_pembayaran_spp.spp_bulan", "asc");
      return $this->db->get();
    }
    // function lihatdatasatu($id_tahun)
    // {
    //     $this->db->where("id_tahun",$id_tahun);
    //     return $this->db->get('tb_tahun_ajaran');
    // }
    //
    // function cekdata($id_tahun)
    // {
    //     $this->db->where("id_tahun",$id_tahun);
    //     return $this->db->get('tb_tahun_ajaran')->num_rows();
    // }
    //
    // function tambahdata($array)
    // {
    //     return $this->db->insert('tb_tahun_ajaran',$array);
    // }
    //
    // function editdata($id_tahun,$array)
    // {
    //     $this->db->where("id_tahun",$id_tahun);
    //     return $this->db->update('tb_tahun_ajaran',$array);
    // }
    // function hapus($id_tahun)
    // {
    //     $this->db->where("id_tahun",$id_tahun);
    //     return $this->db->delete('tb_tahun_ajaran');
    // }
}
