<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_informasi extends CI_Model
{
  function __construct()
  {
      parent::__construct();
  }

  function lihatpengumuman()
  {
      return $this->db->get('tb_pengumuman_ortu');
  }

  function data($id_pengumuman)
  {
    $this->db->where("id_pengumuman",$id_pengumuman);
    return $this->db->get('tb_pengumuman_ortu');
  }

  function tambahdata($array)
  {
      return $this->db->insert('tb_pengumuman_ortu',$array);
  }

  function editdata($id_pengumuman,$array)
  {
      $this->db->where("id_pengumuman",$id_pengumuman);
      return $this->db->update('tb_pengumuman_ortu',$array);
  }
  function hapus($id_pengumuman)
  {
      $this->db->where("id_pengumuman",$id_pengumuman);
      return $this->db->delete('tb_pengumuman_ortu');
  }

}
