<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_jenjang extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get tb_role_admin by kode_role
     */
    function lihatdata()
    {
        return $this->db->get('tb_jenjang');
    }

    function lihatdatasatu($jenjang)
    {
        $this->db->where("jenjang",$jenjang);
        return $this->db->get('tb_jenjang');
    }

    function cekdata($jenjang)
    {
        $this->db->where("jenjang",$jenjang);
        return $this->db->get('tb_jenjang')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_jenjang',$array);
    }

    function editdata($jenjang,$array)
    {
        $this->db->where("jenjang",$jenjang);
        return $this->db->update('tb_jenjang',$array);
    }
    function hapus($jenjang)
    {
        $this->db->where("jenjang",$jenjang);
        return $this->db->delete('tb_jenjang');
    }
   /////////////////////////////////////////

   function lihatdatatingkat($jenjang)
   {
        $this->db->where("jenjang",$jenjang);
        return $this->db->get('tb_tingkatjenjang');
   }

   function tambahdatatingkat($array)
   {
       return $this->db->insert('tb_tingkatjenjang',$array);
   }

   function lihatdatasatutingkat($idtingkatjenjang)
   {
       $this->db->where("idtingkatjenjang",$idtingkatjenjang);
       return $this->db->get('tb_tingkatjenjang');
   }

   function lihatdatatingkatan($jenjang)
   {
        $this->db->where('jenjang', $jenjang);
        $this->db->order_by("tingkat","ASC");
        return $this->db->get('tb_tingkatjenjang');
   }

   function cekdatatingkat($jenjang)
    {
        $this->db->where("jenjang",$jenjang);
        return $this->db->get('tb_tingkatjenjang')->num_rows();
    }

    function editdatatingkat($idtingkatjenjang,$array)
    {
        $this->db->where("idtingkatjenjang",$idtingkatjenjang);
        return $this->db->update('tb_tingkatjenjang',$array);
    }
    function hapustingkat($idtingkatjenjang)
    {
        $this->db->where("idtingkatjenjang",$idtingkatjenjang);
        return $this->db->delete('tb_tingkatjenjang');
    }

    function datatingkatajax($jenjang)
    {
        $this->db->where('jenjang', $jenjang);
        $this->db->order_by("tingkat","ASC");
        $hasil = $this->db->get('tb_tingkatjenjang');
        return $hasil->result();
    }

}
