<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_kel_desa extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        $this->db->select('*');
        $this->db->from('tb_kel_desa');
        $this->db->join('tb_kecamatan', 'tb_kel_desa.id_kecamatan=tb_kecamatan.id_kecamatan' );
        $this->db->join('tb_kota_kab', 'tb_kecamatan.id_kota_kab=tb_kota_kab.id_kota_kab');
        $this->db->join('tb_provinsi','tb_kota_kab.id_provinsi=tb_provinsi.id_provinsi');
        return $this->db->get();
    }

    function lihatdatasatu($id_kel_desa)
    {
      $this->db->select('*');
      $this->db->from('tb_kel_desa');
      $this->db->join('tb_kecamatan', 'tb_kel_desa.id_kecamatan=tb_kecamatan.id_kecamatan' );
      $this->db->join('tb_kota_kab', 'tb_kecamatan.id_kota_kab=tb_kota_kab.id_kota_kab');
      $this->db->join('tb_provinsi','tb_kota_kab.id_provinsi=tb_provinsi.id_provinsi');
      $this->db->where("id_kel_desa",$id_kel_desa);
      return $this->db->get();
    }

    function dataprovinsi()
    {
        return $this->db->get('tb_provinsi');
    }

    function datakecamatan($id_kota_kab)
    {
      $this->db->where("id_kota_kab",$id_kota_kab);
      return $this->db->get('tb_kecamatan');
    }

    function datakecamatanajax($id)
    {
      $hasil=$this->db->query("SELECT * FROM tb_kecamatan WHERE id_kota_kab='$id'");
  		return $hasil->result();
    }

    function datakotakab($id_provinsi)
    {
      $this->db->where("id_provinsi",$id_provinsi);
      return $this->db->get('tb_kota_kab');

    }
    function cekdata($id_kecamatan)
    {
        $this->db->where("id_kecamatan",$id_kecamatan);
        return $this->db->get('tb_kecamatan')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_kel_desa',$array);
    }

    function editdata($id_kel_desa,$array)
    {
        $this->db->where("id_kel_desa",$id_kel_desa);
        return $this->db->update('tb_kel_desa',$array);
    }


    function hapus($id_kel_desa)
    {
        $this->db->where("id_kel_desa",$id_kel_desa);
        return $this->db->delete('tb_kel_desa');
    }
}
