<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pekerjaan extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        return $this->db->get('tb_pekerjaan');
    }

    function lihatdatasatu($id_pekerjaan)
    {
        $this->db->where("id_pekerjaan",$id_pekerjaan);
        return $this->db->get('tb_pekerjaan');
    }

    function cekdata($id_pekerjaan)
    {
        $this->db->where("id_pekerjaan",$id_pekerjaan);
        return $this->db->get('tb_pekerjaan')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_pekerjaan',$array);
    }

    function editdata($id_pekerjaan,$array)
    {
        $this->db->where("id_pekerjaan",$id_pekerjaan);
        return $this->db->update('tb_pekerjaan',$array);
    }
    function hapus($id_pekerjaan)
    {
        $this->db->where("id_pekerjaan",$id_pekerjaan);
        return $this->db->delete('tb_pekerjaan');
    }
}
