<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pelanggaran_p extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_pelanggaran_p');
      $this->db->join('tb_santriwati', 'tb_pelanggaran_p.nis_santri = tb_santriwati.nis_lokal');
      $this->db->where('tb_pelanggaran_p.nis_santri', $nis);

      return $this->db->get();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_pelanggaran_p',$array);
    }

    function ambildata($id)
    {
        $this->db->select('*');
        $this->db->from('tb_pelanggaran_p');
        $this->db->where('id_pelanggaran', $id);
          return $this->db->get();
    }

    function editdata($id,$array)
    {
        $this->db->where("id_pelanggaran",$id);
        return $this->db->update('tb_pelanggaran_p',$array);
    }

    function hapus($id)
    {
        $this->db->where("id_pelanggaran",$id);
        return $this->db->delete('tb_pelanggaran_p');
    }
}
