<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pendidikan extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        return $this->db->get('tb_pendidikan');
    }

    function lihatdatasatu($id_pendidikan)
    {
        $this->db->where("id_pendidikan",$id_pendidikan);
        return $this->db->get('tb_pendidikan');
    }

    function cekdata($id_pendidikan)
    {
        $this->db->where("id_pendidikan",$id_pendidikan);
        return $this->db->get('tb_pendidikan')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_pendidikan',$array);
    }

    function editdata($id_pendidikan,$array)
    {
        $this->db->where("id_pendidikan",$id_pendidikan);
        return $this->db->update('tb_pendidikan',$array);
    }
    function hapus($id_pendidikan)
    {
        $this->db->where("id_pendidikan",$id_pendidikan);
        return $this->db->delete('tb_pendidikan');
    }

    public function upload_contoh($filename){
      ini_set('memory_limit', '-1');
      $inputFileName = './assets/import/'.$filename;
        try {
        $objPHPExcel = PHPExcel_IOFactory::load($inputFileName);
        } catch(Exception $e) {
        die('Error loading file :' . $e->getMessage());
        }

        $worksheet = $objPHPExcel->getActiveSheet()->toArray(null,true,true,true);
        $numRows = count($worksheet);

        for ($i=1; $i < ($numRows+1) ; $i++) {


            $ins = array(
                    "id_pendidikan"          => $worksheet[$i]["A"],
                    "nama_pendidikan"   => $worksheet[$i]["B"]
                   );

            $this->db->insert('tb_pendidikan', $ins);
    }
}
}
