<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pondokan extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get tb_role_admin by kode_role
     */
    function lihatdata()
    {
        return $this->db->get('tb_pondokan');
    }

    function lihatdatasatu($pondokan)
    {
        $this->db->where("pondokan",$pondokan);
        return $this->db->get('tb_pondokan');
    }

    function cekdata($pondokan)
    {
        $this->db->where("pondokan",$pondokan);
        return $this->db->get('tb_pondokan')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_pondokan',$array);
    }

    function editdata($pondokan,$array)
    {
        $this->db->where("pondokan",$pondokan);
        return $this->db->update('tb_pondokan',$array);
    }
    function hapus($pondokan)
    {
        $this->db->where("pondokan",$pondokan);
        return $this->db->delete('tb_pondokan');
    }
   /////////////////////////////////////////

   function lihatdatatingkat($pondokan)
   {
        $this->db->where("pondokan",$pondokan);
        return $this->db->get('tb_tingkatpondokan');
   }

   function tambahdatatingkat($array)
   {
       return $this->db->insert('tb_tingkatpondokan',$array);
   }

   function lihatdatasatutingkat($idtingkatpondokan)
   {
       $this->db->where("idtingkatpondokan",$idtingkatpondokan);
       return $this->db->get('tb_tingkatpondokan');
   }

   function lihatdatatingkatan($pondokan)
   {
        $this->db->where('pondokan', $pondokan);
        $this->db->order_by("tingkat","ASC");
        return $this->db->get('tb_tingkatpondokan');
   }

   function cekdatatingkat($pondokan)
    {
        $this->db->where("pondokan",$pondokan);
        return $this->db->get('tb_tingkatpondokan')->num_rows();
    }

    function editdatatingkat($idtingkatpondokan,$array)
    {
        $this->db->where("idtingkatpondokan",$idtingkatpondokan);
        return $this->db->update('tb_tingkatpondokan',$array);
    }
    function hapustingkat($idtingkatpondokan)
    {
        $this->db->where("idtingkatpondokan",$idtingkatpondokan);
        return $this->db->delete('tb_tingkatpondokan');
    }

    function datatingkatajax($pondokan)
    {
        $this->db->where('pondokan', $pondokan);
        $this->db->order_by("tingkat","ASC");
        $hasil = $this->db->get('tb_tingkatpondokan');
        return $hasil->result();
    }

}
