<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_provinsi extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        return $this->db->get('tb_provinsi');
    }

    function lihatdatasatu($id_provinsi)
    {
        $this->db->where("id_provinsi",$id_provinsi);
        return $this->db->get('tb_provinsi');
    }

    function cekdata($id_provinsi)
    {
        $this->db->where("id_provinsi",$id_provinsi);
        return $this->db->get('tb_provinsi')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_provinsi',$array);
    }

    function editdata($id_provinsi,$array)
    {
        $this->db->where("id_provinsi",$id_provinsi);
        return $this->db->update('tb_provinsi',$array);
    }
    function hapus($id_provinsi)
    {
        $this->db->where("id_provinsi",$id_provinsi);
        return $this->db->delete('tb_provinsi');
    }
}
