<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_presensi extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get tb_role_admin by kode_role
     */
    function lihatdata()
    {
        $this->db->from("tb_presensi_kelas");
        $this->db->join("tb_guru","tb_guru.nip_guru=tb_presensi_kelas.nip_guru");
        $this->db->join("tb_kelas","tb_kelas.kd_kelas=tb_presensi_kelas.kd_kelas");
        $this->db->join("tb_tahun_ajaran","tb_tahun_ajaran.id_tahun=tb_presensi_kelas.id_tahun");
        return $this->db->get();
    }

    function lihatdatasatu($id_kelas_belajar)
    {
        $this->db->where("id_kelas_belajar",$id_kelas_belajar);
        return $this->db->get('tb_presensi_kelas');
    }

    function cekdata($nip)
    {
        $this->db->where("nip_guru",$nip);
        return $this->db->get('tb_guru')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_presensi_kelas',$array);
    }

    function editdata($id,$array)
    {
        $this->db->where("id_kelas_belajar",$id);
        return $this->db->update('tb_presensi_kelas',$array);
    }
    function hapus($id)
    {
        $this->db->where("id_kelas_belajar",$id);
        return $this->db->delete('tb_presensi_kelas');
    }
   /////////////////////////////////////////

   function lihatdataberkas($nip)
   {
        $this->db->where("nip_guru",$nip);
        return $this->db->get('tb_berkas_guru');
   }

   function tambahdataberkas($array)
   {
       return $this->db->insert('tb_berkas_guru',$array);
   }

   function lihatdatasatuberkas($id_berkas)
   {
       $this->db->where("id_berkas",$id_berkas);
       return $this->db->get('tb_berkas_guru');
   }

   function cekdataberkas($id_berkas)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->get('tb_berkas_guru')->num_rows();
    }

    function editdataaberkas($id_berkas,$array)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->update('tb_berkas_guru',$array);
    }
    function hapusberkas($id_berkas)
    {
        $this->db->where("id_berkas",$id_berkas);
        return $this->db->delete('tb_berkas_guru');
    }

}
