<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class m_rekap_guru extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    // function datapelajaran()
    // {
    //     $this->db->select('*');
    //     $this->db->from('tb_presensi_jadwal_afilasi');
    //     $this->db->join('tb_pelajaran', 'tb_presensi_jadwal_afilasi.id_mata_pelajaran = tb_pelajaran.id_mata_pelajaran');
    //     $this->db->join('tb_presensi_kelas', 'tb_presensi_jadwal_afilasi.id_kelas_belajar = tb_presensi_kelas.id_kelas_belajar');
    //     $this->db->join('tb_mata_pelajaran', 'tb_pelajaran.id_mata_pelajaran = tb_mata_pelajaran.id_mata_pelajaran');
    //     $this->db->join('tb_guru', 'tb_pelajaran.nip_guru = tb_guru.nip_guru');
    //     return $this->db->get();
    // }

    function rekapguru($pel,$kel)
    {
      $this->db->select('*');
      $this->db->from('tb_presensi_rekap_guru_afilasi');
      $this->db->join('tb_pelajaran', 'tb_presensi_rekap_guru_afilasi.id_pelajaran = tb_pelajaran.id_pelajaran');
      $this->db->join('tb_presensi_kelas', 'tb_presensi_rekap_guru_afilasi.id_kelas = tb_presensi_kelas.id_kelas_belajar');
      $this->db->join('tb_mata_pelajaran', 'tb_pelajaran.id_mata_pelajaran = tb_mata_pelajaran.id_mata_pelajaran');
      $this->db->join('tb_guru', 'tb_pelajaran.nip_guru = tb_guru.nip_guru');
      $this->db->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel);
      $this->db->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel);
      return $this->db->get();
    }

    function rekapgurup($pel,$kel)
    {
      $this->db->select('*');
      $this->db->from('tb_presensi_rekap_guru_afilasi');
      $this->db->join('tb_pelajaran', 'tb_presensi_rekap_guru_afilasi.id_pelajaran = tb_pelajaran.id_pelajaran');
      $this->db->join('tb_presensi_kelas_p', 'tb_presensi_rekap_guru_afilasi.id_kelas = tb_presensi_kelas_p.id_kelas_belajar');
      $this->db->join('tb_mata_pelajaran', 'tb_pelajaran.id_mata_pelajaran = tb_mata_pelajaran.id_mata_pelajaran');
      $this->db->join('tb_guru', 'tb_pelajaran.nip_guru = tb_guru.nip_guru');
      $this->db->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel);
      $this->db->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel);
      return $this->db->get();
    }

    function dataguru($nip){
      $this->db->select('nama_lengkap');
      $this->db->from('tb_guru');
      $this->db->where("nip_guru",$nip);
      $query = $this->db->get();
      $data = $query->row_array();
      $value = $data['nama_lengkap'];
      return $value;
    }

    function cekdata($nis,$pel,$kel,$tgl){
      $this->db->select('id_santri');
      $this->db->from('tb_presensi_rekap_santri');
      $this->db->where('id_santri', $nis);
      $this->db->where('id_mata_pelajaran', $pel);
      $this->db->where('id_kelas', $kel);
      $this->db->where('tanggal_rekap', $tgl);
      $query = $this->db->get();
      $data = $query->row_array();
      $value = $data['id_santri'];
      return $value;
    }

    // function lihatsantrisatu($nis)
    // {
    //     $this->db->select('nama_lengkap');
    //     $this->db->from('tb_santri');
    //     $this->db->where("nis_lokal",$nis);
    //     $query = $this->db->get();
    //     $data = $query->row_array();
    //     $value = $data['nama_lengkap'];
    //     return $value;
    // }

    function tambahdata($array)
    {
        return $this->db->insert('tb_presensi_rekap_guru_afilasi',$array);
    }

    function pelajaran($pel){
      $this->db->select('nama_mata_pelajaran');
      $this->db->from('tb_mata_pelajaran');
      $this->db->join('tb_pelajaran', 'tb_pelajaran.id_mata_pelajaran = tb_mata_pelajaran.id_mata_pelajaran');
      $this->db->where('tb_pelajaran.id_pelajaran', $pel);
      $query = $this->db->get();
      $data = $query->row_array();
      $value = $data['nama_mata_pelajaran'];
      return $value;
    }

    function kelas($kel){
      $this->db->select('nama_kelas_belajar');
      $this->db->from('tb_presensi_kelas');
      $this->db->where('tb_presensi_kelas.id_kelas_belajar', $kel);
      $query = $this->db->get();
      $data = $query->row_array();
      $value = $data['nama_kelas_belajar'];
      return $value;
    }

    function hapus($id_rekap)
    {
        $this->db->where("id_rekap",$id_rekap);
        return $this->db->delete('tb_presensi_rekap_guru_afilasi');
    }

    function totalhadir($pel,$kel){
      $this->db->select('count(*) as total')
        ->from('tb_presensi_rekap_guru_afilasi')
          ->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel)
          ->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel)

        ->where('status_presensi', 'hadir');
        return $this->db->get()
          ->row_array();
    }

    function totalizin($pel,$kel){
      $this->db->select('count(*) as total')
        ->from('tb_presensi_rekap_guru_afilasi')
        ->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel)
        ->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel)

        ->where('status_presensi', 'izin');
        return $this->db->get()
          ->row_array();
    }

    function totalsakit($pel,$kel){
      $this->db->select('count(*) as total')
        ->from('tb_presensi_rekap_guru_afilasi')
        ->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel)
        ->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel)
        ->where('status_presensi', 'sakit');
        return $this->db->get()
          ->row_array();
    }

    function totalalfa($pel,$kel){
      $this->db->select('count(*) as total')
        ->from('tb_presensi_rekap_guru_afilasi')
        ->where('tb_presensi_rekap_guru_afilasi.id_pelajaran',$pel)
        ->where('tb_presensi_rekap_guru_afilasi.id_kelas',$kel)
        ->where('status_presensi', 'alfa');
        return $this->db->get()
          ->row_array();
    }
}
