<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class m_rekap_santri extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function datapelajaran()
    {
        $this->db->select('*');
        $this->db->from('tb_presensi_jadwal');
        $this->db->join('tb_pelajaran', 'tb_presensi_jadwal.id_pelajaran = tb_pelajaran.id_pelajaran');
        $this->db->join('tb_presensi_kelas', 'tb_presensi_jadwal.id_kelas_belajar = tb_presensi_kelas.id_kelas_belajar');
        $this->db->join('tb_mata_pelajaran', 'tb_pelajaran.id_mata_pelajaran = tb_mata_pelajaran.id_mata_pelajaran');
        $this->db->join('tb_guru', 'tb_pelajaran.nip_guru = tb_guru.nip_guru');
        return $this->db->get();
    }

    function detilinfaq($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_pembayaran_spp');
      $this->db->join('tb_santri', 'tb_pembayaran_spp.nis_santri = tb_santri.nis_lokal');
      $this->db->where('tb_pembayaran_spp.nis_santri', $nis);

      return $this->db->get();
    }

    function datasantri(){
      $this->db->select('nis_lokal, nama_lengkap');
      $this->db->from('tb_santri');
      return $this->db->get();
    }

    function lihatsantrisatu($nis)
    {
        $this->db->select('nama_lengkap');
        $this->db->from('tb_santri');
        $this->db->where("nis_lokal",$nis);
        $query = $this->db->get();
        $data = $query->row_array();
        $value = $data['nama_lengkap'];
        return $value;
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_pembayaran_spp',$array);
    }

    function santribayar($tahun,$bulan){
      $this->db->select('count(*) as total')
        ->from('tb_pembayaran_spp')
        ->where('tb_pembayaran_spp.spp_tahun', $tahun)
        ->where('tb_pembayaran_spp.spp_bulan', $bulan);
        return $this->db->get()
          ->row_array();
    }

    //
    // function editdata($id_tahun,$array)
    // {
    //     $this->db->where("id_tahun",$id_tahun);
    //     return $this->db->update('tb_tahun_ajaran',$array);
    // }
    function hapus($id_infaq)
    {
        $this->db->where("id_pembayaran",$id_infaq);
        return $this->db->delete('tb_pembayaran_spp');
    }
}
