<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_tahun_ajaran extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        return $this->db->get('tb_tahun_ajaran');
    }

    function lihatdatasatu($id_tahun)
    {
        $this->db->where("id_tahun",$id_tahun);
        return $this->db->get('tb_tahun_ajaran');
    }

    function cekdata($id_tahun)
    {
        $this->db->where("id_tahun",$id_tahun);
        return $this->db->get('tb_tahun_ajaran')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_tahun_ajaran',$array);
    }

    function editdata($id_tahun,$array)
    {
        $this->db->where("id_tahun",$id_tahun);
        return $this->db->update('tb_tahun_ajaran',$array);
    }
    function hapus($id_tahun)
    {
        $this->db->where("id_tahun",$id_tahun);
        return $this->db->delete('tb_tahun_ajaran');
    }
}
