<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_berkas extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


        function ambilberkas($email)
        {
            $this->db->where("email_pendaftar",$email);
            return $this->db->get('tb_berkas_pendaftar');
        }

    function ambilberkaspoto($email)
    {
        $this->db->where("email_pendaftar",$email);
        $this->db->where("nama_berkas","paspoto");
        return $this->db->get('tb_berkas_pendaftar');
    }

    function ambilberkaspiagam1($email)
    {
        $this->db->where("email_pendaftar",$email);
        $this->db->where("nama_berkas","piagam1");
        return $this->db->get('tb_berkas_pendaftar');
    }

    function ambilberkaspiagam2($email)
    {
        $this->db->where("email_pendaftar",$email);
        $this->db->where("nama_berkas","piagam2");
        return $this->db->get('tb_berkas_pendaftar');
    }

    function ambilberkaskk($email)
    {
        $this->db->where("email_pendaftar",$email);
        $this->db->where("nama_berkas","kartu keluarga");
        return $this->db->get('tb_berkas_pendaftar');
    }

    function ambilberkasijazah($email)
    {
        $this->db->where("email_pendaftar",$email);
        $this->db->where("nama_berkas","ijazah");
        return $this->db->get('tb_berkas_pendaftar');
    }
    function addberkas($data)
    {
        return $this->db->insert('tb_berkas_pendaftar',$data);
    }

    function editberkas($email,$nama_berkas,$data){
      $this->db->where("email_pendaftar",$email);
      $this->db->where("nama_berkas",$nama_berkas);
      return $this->db->update('tb_berkas_pendaftar',$data);
    }

    function cekberkas($email,$nama_berkas){
      $this->db->where("email_pendaftar",$email);
      $this->db->where("nama_berkas",$nama_berkas);
      return $this->db->get('tb_berkas_pendaftar')->num_rows();
    }

    function editakun($email,$array){
        $this->db->where("email_pendaftar",$email);
        return $this->db->update('tb_akun_pendaftar',$array);
      }

}
?>
