<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_loginsantri extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    function cekemail($email){
      $query = $this->db->query('SELECT * FROM tb_akun_pendaftar where email_pendaftar="'.$email.'"');
      return $query;
    }

    function ceklogin($email,$katasandi) {
      $query = $this->db->query('SELECT * FROM tb_akun_pendaftar where email_pendaftar="'.$email.'" and kata_sandi="'.$katasandi.'"');
      return $query;
          }

    // end


}
?>
