<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_loginsantri extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function cekemail($email) {
            $this->db->where("email_pendaftar", $email);
            return $this->db->get("tb_akun_pendaftar");
          }

    
    // end


}
?>
