<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pendaftaran extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get tb_role_admin by kode_role
     */
    function lihatdatasemua($tahunajaran)
    {
        $this->db->select('*')
       ->from('tb_akun_pendaftar')
       ->join('tb_biodata_pendaftar','tb_akun_pendaftar.email_pendaftar = tb_biodata_pendaftar.email_pendaftar')
       ->where("tb_akun_pendaftar.tahun_ajaran",$tahunajaran);
        return $this->db->get();
    }

    function lihatsemuabiodata($email)
    {
         $this->db->select('*')
       ->from('tb_akun_pendaftar')
       ->join('tb_biodata_pendaftar','tb_akun_pendaftar.email_pendaftar = tb_biodata_pendaftar.email_pendaftar');
       $this->db->where('tb_akun_pendaftar.email_pendaftar',$email);
        return $this->db->get();
    }


      //////////////////////////////////

}
