<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_pembayaran extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

   

    function ambilpembayaran($email)
    {
        $this->db->where("email_pendaftar",$email);
        return $this->db->get('tb_bayar_pendaftar');
    }
    function edit($email,$data)
    {
        $this->db->where("email_pendaftar",$email);
        return $this->db->update('tb_bayar_pendaftar',$data);
    }
    function editakun($email,$array){
        $this->db->where("email_pendaftar",$email);
        return $this->db->update('tb_akun_pendaftar',$array);
      }

}
?>
