<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_santri extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_count_akun() {
      $query = $this->db->query('SELECT * FROM tb_akun_pendaftar');
      return $query->num_rows();

    }
}
?>
