<?php defined('BASEPATH') OR exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_login extends CI_Model{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

    function mloginaksi($data)
    {
        $query = $this->db->get_where('tb_akun_admin', $data);
        return $query;
        // $username = $data['username'];
        // $password = $data['password'];
        // $this->db->query('WHERE BINARY username = BINARY $username AND BINARY password = BINARY $data');
    }

}
?>
