<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Pengaturan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_tb_pengaturan()
    {

        return $this->db->get_where('tb_pengaturan_pendaftaran',array('id_pengaturan'=>1))->row_array();
    }

    function update_tb_pengaturan_pendaftran($params)
    {
        $this->db->where('id_pengaturan',1);
        return $this->db->update('tb_pengaturan_pendaftaran',$params);
    }

}
?>
