<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_dashboard extends CI_Model{
    function __construct(){
        parent::__construct();
    }

    function lihatubahsandi($nis_lokal){
        $this->db->select('nis_lokal, nama_ortu, kata_sandi');
        $this->db->from('tb_akun_ortu');
        $this->db->where("nis_lokal",$nis_lokal);
        return $this->db->get();
    }

    function cekubahsandi($nis_lokal){
        $query = $this->db->where(['nis_lokal'=>$nis_lokal])
                          ->get('tb_akun_ortu');
        if($query->num_rows() > 0){
          return $query->row();
        }
    }

    function ubahsandi($nis_lokal, $kata_sandi, $kata_sandibr)
    {
        $this->db->set("kata_sandi",$kata_sandibr);
        $this->db->where("nis_lokal",$nis_lokal);
        $this->db->where("kata_sandi",$kata_sandi);
        return $this->db->update('tb_akun_ortu');
    }

    function bayarspp($nis,$bulanini,$tahunini)
    {
        $this->db->select('status_bayar');
        $this->db->from('tb_pembayaran_spp');
        $this->db->join('tb_santri', 'tb_pembayaran_spp.nis_santri = tb_santri.nis_lokal');
        $this->db->where('tb_santri.nis_lokal', $nis);
        $this->db->where('tb_pembayaran_spp.spp_bulan', $bulanini);
        $this->db->where('tb_pembayaran_spp.spp_tahun', $tahunini);
        return $this->db->get()
        ->row_array();
    }

    function lihatinfo()
    {
        $this->db->select('*');
        $this->db->from('tb_pengumuman_ortu');
        $this->db->order_by('tanggal_pengumuman','desc');
        $this->db->limit(3);
        return $this->db->get();

    }


      //////////////////////////////////

}
