<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_dashboard extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function bayarspp($nis,$bulanini,$tahunini)
    {
        $this->db->select('status_bayar');
        $this->db->from('tb_pembayaran_spp');
        $this->db->join('tb_santri', 'tb_pembayaran_spp.nis_santri = tb_santri.nis_lokal');
        $this->db->where('tb_santri.nis_lokal', $nis);
        $this->db->where('tb_pembayaran_spp.spp_bulan', $bulanini);
        $this->db->where('tb_pembayaran_spp.spp_tahun', $tahunini);
        return $this->db->get()
        ->row_array();
    }

    function lihatinfo()
    {
        $this->db->select('*');
        $this->db->from('tb_pengumuman_ortu');
        $this->db->order_by('tanggal_pengumuman','desc');
        $this->db->limit(3);
        return $this->db->get();

    }


      //////////////////////////////////

}
