<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_infaq_p extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdatasatu($nis)
    {
        $this->db->select('*');
        $this->db->from('tb_pembayaran_spp_p');
        $this->db->join('tb_santriwati', 'tb_pembayaran_spp_p.nis_santri = tb_santriwati.nis_lokal');
        $this->db->where('tb_santriwati.nis_lokal', $nis);
        return $this->db->get();
    }


      //////////////////////////////////

}
