<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_perizinan extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatperizinan($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_perizinan_keluar');
      $this->db->join('tb_santri', 'tb_perizinan_keluar.nis_santri = tb_santri.nis_lokal');
      $this->db->join('tb_perizinan_penjemput', 'tb_perizinan_keluar.id_penjemput = tb_perizinan_penjemput.id_penjemput');
      $this->db->where('tb_perizinan_keluar.nis_santri', $nis);

      return $this->db->get();
    }

    function lihatdenda($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_perizinan_denda');
      $this->db->join('tb_perizinan_kembali', 'tb_perizinan_denda.id_kembali = tb_perizinan_kembali.id_kembali');
      $this->db->join('tb_perizinan_keluar', 'tb_perizinan_kembali.id_keluar = tb_perizinan_keluar.id_keluar');
      $this->db->join('tb_santri', 'tb_perizinan_keluar.nis_santri = tb_santri.nis_lokal');
      $this->db->join('tb_perizinan_penjemput', 'tb_perizinan_keluar.id_penjemput = tb_perizinan_penjemput.id_penjemput');
      $this->db->where('tb_perizinan_keluar.nis_santri', $nis);
      return $this->db->get();
    }

    // function tambahdata($array)
    // {
    //     return $this->db->insert('tb_prestasi',$array);
    // }
    //
    // function ambildata($id)
    // {
    //     $this->db->select('*');
    //     $this->db->from('tb_prestasi');
    //     $this->db->where('id_prestasi', $id);
    //       return $this->db->get();
    // }
    //
    // function editdata($id,$array)
    // {
    //     $this->db->where("id_prestasi",$id);
    //     return $this->db->update('tb_prestasi',$array);
    // }
    //
    // function hapus($id)
    // {
    //     $this->db->where("id_prestasi",$id);
    //     return $this->db->delete('tb_prestasi');
    // }
}
