<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_prestasi_pelanggaran_p extends CI_Model

{
    function __construct()
    {
        parent::__construct();
    }

    function lihatprestasi($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_prestasi_p');
      $this->db->join('tb_santriwati', 'tb_prestasi_p.nis_santri = tb_santriwati.nis_lokal');
      $this->db->where('tb_prestasi_p.nis_santri', $nis);
      return $this->db->get();
    }

    function lihatpelanggaran($nis)
    {
      $this->db->select('*');
      $this->db->from('tb_pelanggaran_p');
      $this->db->join('tb_santriwati', 'tb_pelanggaran_p.nis_santri = tb_santriwati.nis_lokal');
      $this->db->where('tb_pelanggaran_p.nis_santri', $nis);

      return $this->db->get();
    }

    // function tambahdata($array)
    // {

    //     return $this->db->insert('tb_prestasi',$array);

    //     return $this->db->insert('tb_prestasi_p',$array);

    // }
    //
    // function ambildata($id)
    // {
    //     $this->db->select('*');

    //     $this->db->from('tb_prestasi');

    //     $this->db->from('tb_prestasi_p');

    //     $this->db->where('id_prestasi', $id);
    //       return $this->db->get();
    // }
    //
    // function editdata($id,$array)
    // {
    //     $this->db->where("id_prestasi",$id);

    //     return $this->db->update('tb_prestasi',$array);

    //     return $this->db->update('tb_prestasi_p',$array);

    // }
    //
    // function hapus($id)
    // {
    //     $this->db->where("id_prestasi",$id);

    //     return $this->db->delete('tb_prestasi');

    //     return $this->db->delete('tb_prestasi_p');

    // }
}
