<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Datamaster extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('back-end/m_santri');
        $this->load->library('layout');
    }

      
    function index()
    {
        $this->santri();
    }

    // CRUD Santri
    function santri()
    {
        $variabel['data'] = $this->m_santri->lihatdata();
        $this->layout->render('back-end/santri/v_santri',$variabel,'back-end/santri/v_santri_js');
    }

    function santrilihat()
    {
        $nis = $this->input->get("nis");
        $exec = $this->m_santri->lihatdatasatu($nis);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/santri/v_santri_lihat',$variabel,'back-end/santri/v_santri_js');
        } else {
            redirect(base_url("admin/datamaster/santri"));
        }
        
    }

    function santritambah()
    {
        if ($this->input->post()){

                $array=array(
                    'nis_lokal'=> $this->input->post('nis_lokal'),
                    'email_santri'=> $this->input->post('email_santri'),
                    'nisn'=> $this->input->post('nisn'),
                    'nik'=> $this->input->post('nik'),
                    'nama_lengkap'=>$this->input->post('nama_lengkap'),
                    'tempat_lahir'=>$this->input->post('tempat_lahir'),
                    'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                    'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                    'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                    'provinsi'=>$this->input->post('provinsi'),
                    'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                    'kecamatan'=>$this->input->post('kecamatan'),
                    'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                    'kode_pos'=>$this->input->post('kode_pos'),
                    'hobi'=>$this->input->post('hobi'),
                    'cita_cita'=>$this->input->post('cita_cita'),
                    'jenis_sekolah_asal'=>$this->input->post('jenis_sekolah_asal'),
                    'status_sekolah_asal'=>$this->input->post('status_sekolah_asal'),
                    'nomor_peserta_ujian'=>$this->input->post('nomor_peserta_ujian'),
                    'jarak_ke_sekolah'=>$this->input->post('jarak_ke_sekolah'),
                    'alat_transportasi'=>$this->input->post('alat_transportasi'),
                    'status_tempat_tinggal'=>$this->input->post('status_tempat_tinggal'),
                    'no_kk'=>$this->input->post('no_kk'),
                    'nik_ayah'=>$this->input->post('nik_ayah'),
                    'nama_lengkap_ayah'=>$this->input->post('nama_lengkap_ayah'),
                    'pendidikan_terakhir_ayah'=>$this->input->post('pendidikan_terakhir_ayah'),
                    'pekerjaan_ayah'=>$this->input->post('pekerjaan_ayah'),
                    'nik_ibu'=>$this->input->post('nik_ibu'),
                    'nama_lengkap_ibu'=>$this->input->post('nama_lengkap_ibu'),
                    'pendidikan_terakhir_ibu'=>$this->input->post('pendidikan_terakhir_ibu'),
                    'pekerjaan_ibu'=>$this->input->post('pekerjaan_ibu'),
                    'penghasilan_orang_tua'=>$this->input->post('penghasilan_orang_tua'),
                    'nik_wali'=>$this->input->post('nik_wali'),
                    'nama_lengkap_wali'=>$this->input->post('nama_lengkap_wali'),
                    'pendidikan_terakhir_wali'=>$this->input->post('pendidikan_terakhir_wali'),
                    'pekerjaan_wali'=>$this->input->post('pekerjaan_wali'),
                    'penghasilan_wali'=>$this->input->post('penghasilan_wali'),
                    'jumlah_saudara_kandung'=>$this->input->post('jumlah_saudara_kandung')
                    );
            if ($this->m_santri->cekdata($this->input->post('nis_lokal'))==0) {
                $exec = $this->m_santri->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/santritambah?msg=1"));
                else redirect(base_url("admin/datamaster/santritambah?msg=0"));
            } else {
                $variabel['nis_lokal'] =$this->input->post('nis_lokal');
                $this->layout->render('back-end/santri/v_santritambah',$variabel,'back-end/santri/v_santri_js');
            }

        } else {
            $variabel ='';
            $this->layout->render('back-end/santri/v_santritambah',$variabel,'back-end/santri/v_santri_js');
        }
    }

    function santriedit()
    {
        if ($this->input->post()) {
            $array=array(
                'nis_lokal'=> $this->input->post('nis_lokal'),
                'email_santri'=> $this->input->post('email_santri'),
                'nisn'=> $this->input->post('nisn'),
                'nik'=> $this->input->post('nik'),
                'nama_lengkap'=>$this->input->post('nama_lengkap'),
                'tempat_lahir'=>$this->input->post('tempat_lahir'),
                'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                'provinsi'=>$this->input->post('provinsi'),
                'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                'kecamatan'=>$this->input->post('kecamatan'),
                'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                'kode_pos'=>$this->input->post('kode_pos'),
                'hobi'=>$this->input->post('hobi'),
                'cita_cita'=>$this->input->post('cita_cita'),
                'jenis_sekolah_asal'=>$this->input->post('jenis_sekolah_asal'),
                'status_sekolah_asal'=>$this->input->post('status_sekolah_asal'),
                'nomor_peserta_ujian'=>$this->input->post('nomor_peserta_ujian'),
                'jarak_ke_sekolah'=>$this->input->post('jarak_ke_sekolah'),
                'alat_transportasi'=>$this->input->post('alat_transportasi'),
                'status_tempat_tinggal'=>$this->input->post('status_tempat_tinggal'),
                'no_kk'=>$this->input->post('no_kk'),
                'nik_ayah'=>$this->input->post('nik_ayah'),
                'nama_lengkap_ayah'=>$this->input->post('nama_lengkap_ayah'),
                'pendidikan_terakhir_ayah'=>$this->input->post('pendidikan_terakhir_ayah'),
                'pekerjaan_ayah'=>$this->input->post('pekerjaan_ayah'),
                'nik_ibu'=>$this->input->post('nik_ibu'),
                'nama_lengkap_ibu'=>$this->input->post('nama_lengkap_ibu'),
                'pendidikan_terakhir_ibu'=>$this->input->post('pendidikan_terakhir_ibu'),
                'pekerjaan_ibu'=>$this->input->post('pekerjaan_ibu'),
                'penghasilan_orang_tua'=>$this->input->post('penghasilan_orang_tua'),
                'nik_wali'=>$this->input->post('nik_wali'),
                'nama_lengkap_wali'=>$this->input->post('nama_lengkap_wali'),
                'pendidikan_terakhir_wali'=>$this->input->post('pendidikan_terakhir_wali'),
                'pekerjaan_wali'=>$this->input->post('pekerjaan_wali'),
                'penghasilan_wali'=>$this->input->post('penghasilan_wali'),
                'jumlah_saudara_kandung'=>$this->input->post('jumlah_saudara_kandung')
                );
            $nis2 = $this->input->post("nis_lokal2");
            $nis = $this->input->post("nis_lokal");
            if (($this->m_santri->cekdata($nis)>0) && ($nis2!=$nis)) {
                $variabel['nis_lokal'] =$this->input->post('nis_lokal');
                $variabel['nis_lokal2'] =$this->input->post('nis_lokal2');
                $variabel['data'] = $array;
                $this->layout->render('back-end/santri/v_santri_edit',$variabel,'back-end/santri/v_santri_js');
            } else {
                $exec = $this->m_santri->editdata($nis2,$array);
                if ($exec){
                  redirect(base_url("admin/datamaster/santriedit?nis=".$nis."&msg=1"));
                }
            }
      } else {
            $nis = $this->input->get("nis");
            $exec = $this->m_santri->lihatdatasatu($nis);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/santri/v_santri_edit',$variabel,'back-end/santri/v_santri_js');
            } else {
                redirect(base_url("admin/datamaster/santri"));
            }
      }
        
    }

    function santrihapus()
    {
       $nis = $this->input->get("nis");
       $exec = $this->m_santri->hapus($nis);
       redirect(base_url()."admin/datamaster/santri?msg=1");
    }

    // End CRUD Santri
  

}
