<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class Datamaster extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library(array('form_validation','session'));
        $this->load->model('back-end/datamaster/m_admin');
        $this->load->model('back-end/datamaster/m_santri');
        $this->load->model('back-end/datamaster/m_guru');
        $this->load->model('back-end/datamaster/m_staff');
        $this->load->model('back-end/datamaster/m_provinsi');
        $this->load->model('back-end/datamaster/m_pendidikan');
        $this->load->model('back-end/datamaster/m_pekerjaan');
        $this->load->model('back-end/datamaster/m_alat_transportasi');
        $this->load->model('back-end/datamaster/m_kota_kab');
        $this->load->model('back-end/datamaster/m_kecamatan');
        $this->load->model('back-end/datamaster/m_kel_desa');
        $this->load->model('back-end/datamaster/m_tahun_ajaran');
        $this->load->model('back-end/datamaster/m_kelas');
        $this->load->model('back-end/datamaster/m_matpel');
        $this->load->model('back-end/datamaster/m_infaq');
        $this->load->library('layout');
        $this->load->helper('indo_helper');
        if ($this->session->userdata('nama_akun')=="") {
            redirect('admin/login/loginhalaman');
        }
        else if ($this->session->userdata('kode_role_admin') == 'adm_pd') {
            redirect('admin/pendaftaran');
        }
        else if ($this->session->userdata('kode_role_admin') == 'adm_prz') {
            redirect('admin/perizinan');
        }
        $this->load->helper('text');
    }


    function index()
    {
        $variabel['nama_akun'] = $this->session->userdata('nama_akun');
        $this->layout->render('back-end/datamaster/dashboard',$variabel);
    }

    function logout(){
        $this->session->unset_userdata('nip_staff_admin');
        $this->session->unset_userdata('nama_akun');
        $this->session->unset_userdata('kode_role_admin');
        session_destroy();
        redirect('admin/login/loginhalaman');
    }

    // CRUD Admin
    function admin(){
       $variabel['data'] = $this->m_admin->lihatdata();
       $this->layout->render('back-end/datamaster/admin/v_admin',$variabel,'back-end/datamaster/admin/v_admin_js');
    }

    function admintambah(){
        if ($this->input->post()){
            $array=array(
                'kode_role_admin'=> $this->input->post('kode_role_admin'),
                'nip_staff_admin'=> $this->input->post('nip_staff_admin'),
                'nama_akun'=> $this->input->post('nama_akun'),
                'kata_sandi'=> md5($this->input->post('kata_sandi')),
                );
            $nama_akun = $this->input->post("nama_akun");
            $kata_sandi = $this->input->post("kata_sandi");
            $rekata_sandi = $this->input->post("rekata_sandi");
            if (($this->m_admin->cekdata($nama_akun)==0) && ($kata_sandi==$rekata_sandi)) {
                $exec = $this->m_admin->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/admintambah?msg=1"));
                else redirect(base_url("admin/datamaster/admintambah?msg=0"));
            } else if ($kata_sandi!=$rekata_sandi) {
                $variabel['nip_staff_admin']=$this->m_admin->ambilstaff();
                $variabel['kode_role_admin']=$this->m_admin->ambilroleadmin();
                $variabel['rekata_sandi'] =$this->input->post("rekata_sandi");
                $this->layout->render('back-end/datamaster/admin/v_admin_tambah',$variabel,'back-end/datamaster/admin/v_admin_js');
            }
            else {
                $variabel['nip_staff_admin']=$this->m_admin->ambilstaff();
                $variabel['kode_role_admin']=$this->m_admin->ambilroleadmin();
                $variabel['nama_akun'] =$this->input->post('nama_akun');
                $this->layout->render('back-end/datamaster/admin/v_admin_tambah',$variabel,'back-end/datamaster/admin/v_admin_js');
            }
        } else {
            //$variabel ='';
            $variabel['nip_staff_admin']=$this->m_admin->ambilstaff();
            $variabel['kode_role_admin']=$this->m_admin->ambilroleadmin();
            $this->layout->render('back-end/datamaster/admin/v_admin_tambah',$variabel,'back-end/datamaster/admin/v_admin_js');
        }
    }

    function adminedit(){
        if ($this->input->post()) {
          $array=array(
              'nama_role'=> $this->input->post('nama_role'),
              'nip_staff_admin'=> $this->input->post('nip_staff_admin'),
              'nama_lengkap'=> $this->input->post('nama_lengkap'),
              'nama_akun'=> $this->input->post('nama_akun'),
              'kata_sandi'=> $this->input->post('kata_sandi'),
              );
            $nama_akun = $this->input->post("nama_akun");
            $kata_sandi = md5($this->input->post("kata_sandi"));
            $kata_sandibr = md5($this->input->post("kata_sandibr"));
            $rekata_sandibr = md5($this->input->post("rekata_sandibr"));
            $query = $this->m_admin->cekdataedit($nama_akun);
            if ($query->kata_sandi!=$kata_sandi) {
                $variabel['kata_sandi'] =$this->input->post('kata_sandi');
                $variabel['data'] = $array;
                $this->layout->render('back-end/datamaster/admin/v_admin_edit',$variabel,'back-end/datamaster/admin/v_admin_js');
            } else if ($kata_sandibr!=$rekata_sandibr){
                 $variabel['rekata_sandibr'] =$this->input->post('rekata_sandibr');
                 $variabel['data'] = $array;
                 $this->layout->render('back-end/datamaster/admin/v_admin_edit',$variabel,'back-end/datamaster/admin/v_admin_js');
            } else {
                $exec = $this->m_admin->editdata($nama_akun,$kata_sandi,$kata_sandibr);
                if ($exec){
                    redirect(base_url("admin/datamaster/adminedit?nama_akun=".$nama_akun."&msg=1"));
                }
            }
        } else {
            $nama_akun = $this->input->get("nama_akun");
            $exec = $this->m_admin->lihatdatasatu($nama_akun);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/datamaster/admin/v_admin_edit',$variabel,'back-end/datamaster/admin/v_admin_js');
            } else {
                redirect(base_url("admin/datamaster/admin"));
            }
        }
    }

    function adminhapus(){
        $nama_akun = $this->input->get("nama_akun");
        $exec = $this->m_admin->hapus($nama_akun);
        redirect(base_url()."admin/datamaster/admin?msg=1");
    }
    // End CRUD Admin

    // CRUD Santri
    function santri()
    {
        $variabel['data'] = $this->m_santri->lihatdata();
        $this->layout->render('back-end/datamaster/santri/v_santri',$variabel,'back-end/datamaster/santri/v_santri_js');
    }

    function santrilihat()
    {
        $nis = $this->input->get("nis");
        $exec = $this->m_santri->lihatdatasatu($nis);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/datamaster/santri/v_santri_lihat',$variabel,'back-end/datamaster/santri/v_santri_js');
        } else {
            redirect(base_url("admin/datamaster/santri"));
        }

    }

    function datakotakab2()
    {
      $id=$this->input->post('provinsi');
      $data=$this->m_santri->datakotaajax($id);
      echo json_encode($data);
    }

    function datakecamatan2()
    {
      $id=$this->input->post('kecamatan');
      $data=$this->m_santri->datakecamatanajax($id);
      echo json_encode($data);
    }

    function datadesa2()
    {
      $id=$this->input->post('desa');
      $data=$this->m_santri->datadesaajax($id);
      echo json_encode($data);
    }


    function santritambah()
    {
        if ($this->input->post()){

                $array=array(
                    'nis_lokal'=> $this->input->post('nis_lokal'),
                    'email_santri'=> $this->input->post('email_santri'),
                    'nisn'=> $this->input->post('nisn'),
                    'nik'=> $this->input->post('nik'),
                    'nama_lengkap'=>$this->input->post('nama_lengkap'),
                    'tempat_lahir'=>$this->input->post('tempat_lahir'),
                    'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                    'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                    'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                    'provinsi'=>$this->input->post('provinsi'),
                    'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                    'kecamatan'=>$this->input->post('kecamatan'),
                    'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                    'kode_pos'=>$this->input->post('kode_pos'),
                    'hobi'=>$this->input->post('hobi'),
                    'cita_cita'=>$this->input->post('cita_cita'),
                    'jenis_sekolah_asal'=>$this->input->post('jenis_sekolah_asal'),
                    'status_sekolah_asal'=>$this->input->post('status_sekolah_asal'),
                    'nomor_peserta_ujian'=>$this->input->post('nomor_peserta_ujian'),
                    'jarak_ke_sekolah'=>$this->input->post('jarak_ke_sekolah'),
                    'alat_transportasi'=>$this->input->post('alat_transportasi'),
                    'status_tempat_tinggal'=>$this->input->post('status_tempat_tinggal'),
                    'no_kk'=>$this->input->post('no_kk'),
                    'nik_ayah'=>$this->input->post('nik_ayah'),
                    'nama_lengkap_ayah'=>$this->input->post('nama_lengkap_ayah'),
                    'pendidikan_terakhir_ayah'=>$this->input->post('pendidikan_terakhir_ayah'),
                    'pekerjaan_ayah'=>$this->input->post('pekerjaan_ayah'),
                    'nik_ibu'=>$this->input->post('nik_ibu'),
                    'nama_lengkap_ibu'=>$this->input->post('nama_lengkap_ibu'),
                    'pendidikan_terakhir_ibu'=>$this->input->post('pendidikan_terakhir_ibu'),
                    'pekerjaan_ibu'=>$this->input->post('pekerjaan_ibu'),
                    'penghasilan_orang_tua'=>$this->input->post('penghasilan_orang_tua'),
                    'nik_wali'=>$this->input->post('nik_wali'),
                    'nama_lengkap_wali'=>$this->input->post('nama_lengkap_wali'),
                    'pendidikan_terakhir_wali'=>$this->input->post('pendidikan_terakhir_wali'),
                    'pekerjaan_wali'=>$this->input->post('pekerjaan_wali'),
                    'penghasilan_wali'=>$this->input->post('penghasilan_wali'),
                    'jumlah_saudara_kandung'=>$this->input->post('jumlah_saudara_kandung'),
                    'hp'=>$this->input->post('hp'),
                    'hpayah'=>$this->input->post('hpayah'),
                    'hpibu'=>$this->input->post('hpibu'),
                    'hpwali'=>$this->input->post('hpwali')
                    );
            if ($this->m_santri->cekdata($this->input->post('nis_lokal'))==0) {
                $exec = $this->m_santri->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/santritambah?msg=1"));
                else redirect(base_url("admin/datamaster/santritambah?msg=0"));
            } else {
                $variabel['provinsi']=$this->m_santri->ambilprovinsi();
                $variabel['kabupaten']=$this->m_santri->ambilkabupaten($this->input->post('provinsi'));
                $variabel['kecamatan']=$this->m_santri->ambilkecamatan($this->input->post('kabupaten_kota'));
                $variabel['desa']=$this->m_santri->ambildesa($this->input->post('kecamatan'));
            $variabel['transportasi']=$this->m_santri->ambiltransportasi();
             $variabel['pekerjaan']=$this->m_santri->ambilpekerjaan();
             $variabel['pendidikan']=$this->m_santri->ambilpendidikan();
                $variabel['nis_lokal'] =$this->input->post('nis_lokal');
                $this->layout->render('back-end/datamaster/santri/v_santri_tambah',$variabel,'back-end/datamaster/santri/v_santri_js');
            }

        } else {
            $variabel['provinsi']=$this->m_santri->ambilprovinsi();
            $variabel['transportasi']=$this->m_santri->ambiltransportasi();
             $variabel['pekerjaan']=$this->m_santri->ambilpekerjaan();
             $variabel['pendidikan']
             =$this->m_santri->ambilpendidikan();
             $variabel['kabupaten']=$this->m_santri->ambilkabupaten("");
             $variabel['kecamatan']=$this->m_santri->ambilkecamatan("");
             $variabel['desa']=$this->m_santri->ambildesa("");

            $this->layout->render('back-end/datamaster/santri/v_santri_tambah',$variabel,'back-end/datamaster/santri/v_santri_js');
        }
    }

    function santriedit()
    {
        if ($this->input->post()) {
            $array=array(
                'nis_lokal'=> $this->input->post('nis_lokal'),
                'email_santri'=> $this->input->post('email_santri'),
                'nisn'=> $this->input->post('nisn'),
                'nik'=> $this->input->post('nik'),
                'nama_lengkap'=>$this->input->post('nama_lengkap'),
                'tempat_lahir'=>$this->input->post('tempat_lahir'),
                'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                'provinsi'=>$this->input->post('provinsi'),
                'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                'kecamatan'=>$this->input->post('kecamatan'),
                'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                'kode_pos'=>$this->input->post('kode_pos'),
                'hobi'=>$this->input->post('hobi'),
                'cita_cita'=>$this->input->post('cita_cita'),
                'jenis_sekolah_asal'=>$this->input->post('jenis_sekolah_asal'),
                'status_sekolah_asal'=>$this->input->post('status_sekolah_asal'),
                'nomor_peserta_ujian'=>$this->input->post('nomor_peserta_ujian'),
                'jarak_ke_sekolah'=>$this->input->post('jarak_ke_sekolah'),
                'alat_transportasi'=>$this->input->post('alat_transportasi'),
                'status_tempat_tinggal'=>$this->input->post('status_tempat_tinggal'),
                'no_kk'=>$this->input->post('no_kk'),
                'nik_ayah'=>$this->input->post('nik_ayah'),
                'nama_lengkap_ayah'=>$this->input->post('nama_lengkap_ayah'),
                'pendidikan_terakhir_ayah'=>$this->input->post('pendidikan_terakhir_ayah'),
                'pekerjaan_ayah'=>$this->input->post('pekerjaan_ayah'),
                'nik_ibu'=>$this->input->post('nik_ibu'),
                'nama_lengkap_ibu'=>$this->input->post('nama_lengkap_ibu'),
                'pendidikan_terakhir_ibu'=>$this->input->post('pendidikan_terakhir_ibu'),
                'pekerjaan_ibu'=>$this->input->post('pekerjaan_ibu'),
                'penghasilan_orang_tua'=>$this->input->post('penghasilan_orang_tua'),
                'nik_wali'=>$this->input->post('nik_wali'),
                'nama_lengkap_wali'=>$this->input->post('nama_lengkap_wali'),
                'pendidikan_terakhir_wali'=>$this->input->post('pendidikan_terakhir_wali'),
                'pekerjaan_wali'=>$this->input->post('pekerjaan_wali'),
                'penghasilan_wali'=>$this->input->post('penghasilan_wali'),
                'jumlah_saudara_kandung'=>$this->input->post('jumlah_saudara_kandung'),
                'hp'=>$this->input->post('hp'),
                'hpayah'=>$this->input->post('hpayah'),
                'hpibu'=>$this->input->post('hpibu'),
                'hpwali'=>$this->input->post('hpwali')
                );
            $nis2 = $this->input->post("nis_lokal2");
            $nis = $this->input->post("nis_lokal");
            if (($this->m_santri->cekdata($nis)>0) && ($nis2!=$nis)) {
                $variabel['nis_lokal'] =$this->input->post('nis_lokal');
                $variabel['nis_lokal2'] =$this->input->post('nis_lokal2');
                $variabel['data'] = $array;
                $this->layout->render('back-end/datamaster/santri/v_santri_edit',$variabel,'back-end/datamaster/santri/v_santri_js');
            } else {
                $exec = $this->m_santri->editdata($nis2,$array);
                if ($exec){
                  redirect(base_url("admin/datamaster/santriedit?nis=".$nis."&msg=1"));
                }
            }
      } else {
            $nis = $this->input->get("nis");
            $exec = $this->m_santri->lihatdatasatu($nis);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/datamaster/santri/v_santri_edit',$variabel,'back-end/datamaster/santri/v_santri_js');
            } else {
                redirect(base_url("admin/datamaster/santri"));
            }
      }

    }

    function santrihapus()
    {
       $nis = $this->input->get("nis");
       $exec = $this->m_santri->hapus($nis);
       redirect(base_url()."admin/datamaster/santri?msg=1");
    }

    function santriberkas()
    {
        $nis = $this->input->get("nis");
        $exec = $this->m_santri->lihatdatasatu($nis);
        if ($exec->num_rows()>0){
            $variabel['santri'] = $exec->row_array();
            $variabel['data'] = $this->m_santri->lihatdataberkas($nis);
            $this->layout->render('back-end/datamaster/santri/v_santriberkas',$variabel,'back-end/datamaster/santri/v_santriberkas_js');
        } else {
            redirect(base_url("admin/datamaster/santri"));
        }

    }

    function santritambahberkas()
    {
        $nis = $this->input->get("nis");
        $exec = $this->m_santri->lihatdatasatu($nis);
        if ($exec->num_rows()>0){
            $variabel['santri'] = $exec->row_array();
            if ($this->input->post()){
                $config['upload_path'] = './assets/berkas/berkassantri';
                $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
                $this->load->library('upload', $config);
                $this->upload->do_upload("file_berkas");
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];

                $nis_lokal = $this->input->post('nis_lokal');
                $nama_berkas = $this->input->post('nama_berkas');
                $array=array(
                    'nis_lokal'=>  $nis_lokal,
                    'nama_berkas'=> $nama_berkas,
                    'file_berkas' => $file_berkas
                    );

                $exec = $this->m_santri->tambahdataberkas($array);
                if ($exec) redirect(base_url("admin/datamaster/santritambahberkas?nis=".$nis_lokal."&msg=1"));
                else redirect(base_url("admin/datamaster/santriberkastambah?nis=".$nis_lokal."&msg=0"));
            } else {

                $this->layout->render('back-end/datamaster/santri/v_santriberkas_tambah',$variabel,'back-end/datamaster/santri/v_santriberkas_js');
            }
        } else {
            redirect(base_url("admin/datamaster/santri"));
        }
    }

    function santrihapusberkas()
    {
        $id_berkas = $this->input->get("id_berkas");
        $nis = $this->input->get("nis");

        $query2 = $this->m_santri->lihatdatasatuberkas($id_berkas);
        $row2 = $query2->row();
        $berkas1temp = $row2->file_berkas;
        $path1 ="./assets/berkas/berkassantri/".$berkas1temp."";
        if(is_file($path1)) {
            unlink($path1);
        }

        $exec = $this->m_santri->hapusberkas($id_berkas);
        redirect(base_url()."admin/datamaster/santriberkas?msg=1&nis=".$nis."");
    }

    function santrieditberkas()
    {
        if ($this->input->post()) {
            $id_berkas = $this->input->post('id_berkas');
            $nama_berkas = $this->input->post('nama_berkas');
            $nis_lokal = $this->input->post('nis_lokal');
            $array=array(
                'nama_berkas'=> $nama_berkas
                );

            $config['upload_path'] = './assets/berkas/berkassantri';
            $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
            $this->load->library('upload', $config);
            if ( $this->upload->do_upload("file_berkas"))
            {
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];
                $array['file_berkas']=$file_berkas;

                $query2 = $this->m_santri->lihatdatasatuberkas($id_berkas);
                $row2 = $query2->row();
                $berkas1temp = $row2->file_berkas;
                $path1 ="./assets/berkas/berkassantri/".$berkas1temp."";
                if(is_file($path1)) {
                    unlink($path1); //menghapus gambar di folder produk
                }
            }
            $exec = $this->m_santri->editdataaberkas($id_berkas,$array);
            if ($exec) redirect(base_url("admin/datamaster/santrieditberkas?id=".$id_berkas."&nis=".$nis_lokal."&msg=1"));
            else redirect(base_url("admin/datamaster/santrieditberkas?id=".$id_berkas."&nis=".$nis_lokal."&msg=0"));

        } else {
            $nis = $this->input->get("nis");
            $id = $this->input->get("id");
            $exec = $this->m_santri->lihatdatasatu($nis);
            if ($exec->num_rows()>0){
                $variabel['santri'] = $exec ->row_array();
                $exec2 = $this->m_santri->lihatdatasatuberkas($id);
                if ($exec2->num_rows()>0){

                    $variabel['data'] = $exec2->row_array();
                    $this->layout->render('back-end/datamaster/santri/v_santriberkas_edit',$variabel,'back-end/datamaster/santri/v_santriberkas_js');
                } else {
                    redirect(base_url("admin/datamaster/santriberkas?nis=$nis"));
                }
            } else {
                redirect(base_url("admin/datamaster/santri"));
            }
        }

    }

    // End CRUD Santri

//CRUD Mata Pelajaran
    function matpel(){
         $variabel['data'] = $this->m_matpel->lihatdata();
        $this->layout->render('back-end/datamaster/matpel/v_matpel',$variabel,'back-end/datamaster/matpel/v_matpel_js');
    }

    function matpellihat()
    {
        $kd_matpel = $this->input->get("kd_matpel");
        $exec = $this->m_matpel->lihatdatasatu($kd_matpel);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/datamaster/matpel/v_matpel_lihat',$variabel,'back-end/datamaster/matpel/v_matpel_js');
        } else {
            redirect(base_url("admin/datamaster/matpel"));
        }
    }
    function matpeltambah()
    {
        if ($this->input->post()){
                $array=array(
                    'kd_matpel'=> NULL,
                    'nama_matpel'=> $this->input->post('nama_matpel'),
                    'tingkat_matpel'=> $this->input->post('tingkat_matpel')
                    );

                $exec = $this->m_matpel->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/matpeltambah?msg=1"));
                else redirect(base_url("admin/datamaster/matpeltambah?msg=0"));
        } else {
            $variabel ='';
            $this->layout->render('back-end/datamaster/matpel/v_matpel_tambah',$variabel,'back-end/datamaster/matpel/v_matpel_js');
        }
    }

    function matpeledit()
    {
        if ($this->input->post()) {
            $kode = $this->input->post('kd_matpel');
            $array=array(
                'nama_matpel'=> $this->input->post('nama_matpel'),
                'tingkat_matpel'=> $this->input->post('tingkat_matpel')
                );
                $exec = $this->m_matpel->editdata($kode,$array);
                if ($exec)
                  redirect(base_url("admin/datamaster/matpeledit?kd_matpel=".$kode."&msg=1"));
                else
                    redirect(base_url("admin/datamaster/matpeledit?kd_matpel=".$kode."&msg=0"));
        }
        else{
            $kode = $this->input->get("kd_matpel");
            $exec = $this->m_matpel->lihatdatasatu($kode);
            if ($exec->num_rows()>0){
                    $variabel['data'] = $exec ->row_array();
                    $this->layout->render('back-end/datamaster/matpel/v_matpel_edit',$variabel,'back-end/datamaster/matpel/v_matpel_js');
            }
            else
                redirect(base_url("admin/datamaster/matpel"));
        }
    }
    function matpelhapus()
    {
       $kode = $this->input->get("kd_matpel");
       $exec = $this->m_matpel->hapus($kode);
       redirect(base_url()."admin/datamaster/matpel?msg=1");
    }
//End CRUD Mata Pelajaran

//CRUD KELAS
   function kelas(){
         $variabel['data'] = $this->m_kelas->lihatdata();
        $this->layout->render('back-end/datamaster/kelas/v_kelas',$variabel,'back-end/datamaster/kelas/v_kelas_js');
   }

    function kelaslihat()
    {
        $kd_kelas = $this->input->get("kd_kelas");
        $exec = $this->m_kelas->lihatdatasatu($kd_kelas);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/datamaster/kelas/v_kelas_lihat',$variabel,'back-end/datamaster/kelas/v_kelas_js');
        } else
            redirect(base_url("admin/datamaster/kelas"));
    }
    function kelastambah()
    {
        if ($this->input->post()){
                $array=array(
                    'kd_kelas'=> NULL,
                    'nama_kelas'=> $this->input->post('nama_kelas'),
                    'tingkat_kelas'=> $this->input->post('tingkat_kelas'),
                    'kapasitas'=>$this->input->post('kapasitas')
                    );

                $exec = $this->m_kelas->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/kelastambah?msg=1"));
                else redirect(base_url("admin/datamaster/kelastambah?msg=0"));
        } else {
            $variabel ='';
            $this->layout->render('back-end/datamaster/kelas/v_kelas_tambah',$variabel,'back-end/datamaster/kelas/v_kelas_js');
        }
    }

    function kelasedit()
    {
        if ($this->input->post()) {
            $kode = $this->input->post('kd_kelas');
            $array=array(
                'nama_kelas'=> $this->input->post('nama_kelas'),
                'tingkat_kelas'=> $this->input->post('tingkat_kelas'),
                'kapasitas'=> $this->input->post('kapasitas')
                );

                $exec = $this->m_kelas->editdata($kode,$array);
                if ($exec)
                  redirect(base_url("admin/datamaster/kelasedit?kd_kelas=".$kode."&msg=1"));
                else
                     redirect(base_url("admin/datamaster/kelasedit?kd_kelas=".$kode."&msg=0"));
        }
        else{
            $kode = $this->input->get("kd_kelas");
            $exec = $this->m_kelas->lihatdatasatu($kode);
            if ($exec->num_rows()>0){
                    $variabel['data'] = $exec ->row_array();
                    $this->layout->render('back-end/datamaster/kelas/v_kelas_edit',$variabel,'back-end/datamaster/kelas/v_kelas_js');
            }
            else
                redirect(base_url("admin/datamaster/kelas"));
        }
    }

    function kelashapus()
    {
       $kode = $this->input->get("kd_kelas");
       $exec = $this->m_kelas->hapus($kode);
       redirect(base_url()."admin/datamaster/kelas?msg=1");
    }
//end CRUD kelas

    // CRUD Guru
    function guru()
    {
        $variabel['data'] = $this->m_guru->lihatdata();
        $this->layout->render('back-end/datamaster/guru/v_guru',$variabel,'back-end/datamaster/guru/v_guru_js');
    }

    function gurulihat()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_guru->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/datamaster/guru/v_guru_lihat',$variabel,'back-end/datamaster/guru/v_guru_js');
        } else {
            redirect(base_url("admin/datamaster/guru"));
        }

    }

    function gurutambah()
    {
        if ($this->input->post()){

                $array=array(
                    'nip_guru'=> $this->input->post('nip_guru'),
                    'email_guru'=> $this->input->post('email_guru'),
                    'hp_guru'=> $this->input->post('hp_guru'),
                    'nama_lengkap'=>$this->input->post('nama_lengkap'),
                    'tempat_lahir'=>$this->input->post('tempat_lahir'),
                    'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                    'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                    'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                    'provinsi'=>$this->input->post('provinsi'),
                    'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                    'kecamatan'=>$this->input->post('kecamatan'),
                    'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                    'kode_pos'=>$this->input->post('kode_pos')
                    );
            if ($this->m_guru->cekdata($this->input->post('nip_guru'))==0) {
                $exec = $this->m_guru->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/gurutambah?msg=1"));
                else redirect(base_url("admin/datamaster/gurutambah?msg=0"));
            } else {
                $variabel['nip_guru'] =$this->input->post('nip_guru');
                $this->layout->render('back-end/datamaster/guru/v_guru_tambah',$variabel,'back-end/datamaster/guru/v_guru_js');
            }

        } else {
            $variabel ='';
            $this->layout->render('back-end/datamaster/guru/v_guru_tambah',$variabel,'back-end/datamaster/guru/v_guru_js');
        }
    }

    function guruedit()
    {
        if ($this->input->post()) {
            $array=array(
                'nip_guru'=> $this->input->post('nip_guru'),
                'email_guru'=> $this->input->post('email_guru'),
                'hp_guru'=> $this->input->post('hp_guru'),
                'nama_lengkap'=>$this->input->post('nama_lengkap'),
                'tempat_lahir'=>$this->input->post('tempat_lahir'),
                'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                'provinsi'=>$this->input->post('provinsi'),
                'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                'kecamatan'=>$this->input->post('kecamatan'),
                'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                'kode_pos'=>$this->input->post('kode_pos')
                );
            $nip2 = $this->input->post("nip_guru2");
            $nip = $this->input->post("nip_guru");
            if (($this->m_guru->cekdata($nip)>0) && ($nip2!=$nip)) {
                $variabel['nip_guru'] =$this->input->post('nip_guru');
                $variabel['nip_guru2'] =$this->input->post('nip_guru2');
                $variabel['data'] = $array;
                $this->layout->render('back-end/datamaster/guru/v_guru_edit',$variabel,'back-end/datamaster/guru/v_guru_js');
            } else {
                $exec = $this->m_guru->editdata($nip2,$array);
                if ($exec){
                  redirect(base_url("admin/datamaster/guruedit?nip=".$nip."&msg=1"));
                }
            }
      } else {
            $nip = $this->input->get("nip");
            $exec = $this->m_guru->lihatdatasatu($nip);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/datamaster/guru/v_guru_edit',$variabel,'back-end/datamaster/guru/v_guru_js');
            } else {
                redirect(base_url("admin/datamaster/guru"));
            }
      }

    }

    function guruhapus()
    {
       $nip = $this->input->get("nip");
       $exec = $this->m_guru->hapus($nip);
       redirect(base_url()."admin/datamaster/guru?msg=1");
    }

    function guruberkas()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_guru->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['guru'] = $exec->row_array();
            $variabel['data'] = $this->m_guru->lihatdataberkas($nip);
            $this->layout->render('back-end/datamaster/guru/v_guruberkas',$variabel,'back-end/datamaster/guru/v_guruberkas_js');
        } else {
            redirect(base_url("admin/datamaster/guru"));
        }

    }

    function gurutambahberkas()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_guru->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['guru'] = $exec->row_array();
            if ($this->input->post()){
                $config['upload_path'] = './assets/berkas/berkasguru';
                $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
                $this->load->library('upload', $config);
                $this->upload->do_upload("file_berkas");
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];

                $nip_guru = $this->input->post('nip_guru');
                $nama_berkas = $this->input->post('nama_berkas');
                $array=array(
                    'nip_guru'=>  $nip_guru,
                    'nama_berkas'=> $nama_berkas,
                    'file_berkas' => $file_berkas
                    );

                $exec = $this->m_guru->tambahdataberkas($array);
                if ($exec) redirect(base_url("admin/datamaster/gurutambahberkas?nip=".$nip_guru."&msg=1"));
                else redirect(base_url("admin/datamaster/guruberkastambah?nip=".$nip_guru."&msg=0"));
            } else {

                $this->layout->render('back-end/datamaster/guru/v_guruberkas_tambah',$variabel,'back-end/datamaster/guru/v_guruberkas_js');
            }
        } else {
            redirect(base_url("admin/datamaster/guru"));
        }
    }

    function guruhapusberkas()
    {
        $id_berkas = $this->input->get("id_berkas");
        $nip = $this->input->get("nip");

        $query2 = $this->m_guru->lihatdatasatuberkas($id_berkas);
        $row2 = $query2->row();
        $berkas1temp = $row2->file_berkas;
        $path1 ="./assets/berkas/berkasguru/".$berkas1temp."";
        if(is_file($path1)) {
            unlink($path1);
        }

        $exec = $this->m_guru->hapusberkas($id_berkas);
        redirect(base_url()."admin/datamaster/guruberkas?msg=1&nip=".$nip."");
    }

    function gurueditberkas()
    {
        if ($this->input->post()) {
            $id_berkas = $this->input->post('id_berkas');
            $nama_berkas = $this->input->post('nama_berkas');
            $nip_guru = $this->input->post('nip_guru');
            $array=array(
                'nama_berkas'=> $nama_berkas
                );

            $config['upload_path'] = './assets/berkas/berkasguru';
            $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
            $this->load->library('upload', $config);
            if ( $this->upload->do_upload("file_berkas"))
            {
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];
                $array['file_berkas']=$file_berkas;

                $query2 = $this->m_guru->lihatdatasatuberkas($id_berkas);
                $row2 = $query2->row();
                $berkas1temp = $row2->file_berkas;
                $path1 ="./assets/berkas/berkasguru/".$berkas1temp."";
                if(is_file($path1)) {
                    unlink($path1); //menghapus gambar di folder produk
                }
            }
            $exec = $this->m_guru->editdataaberkas($id_berkas,$array);
            if ($exec) redirect(base_url("admin/datamaster/gurueditberkas?id=".$id_berkas."&nip=".$nip_guru."&msg=1"));
            else redirect(base_url("admin/datamaster/gurueditberkas?id=".$id_berkas."&nip=".$nip_guru."&msg=0"));

        } else {
            $nip = $this->input->get("nip");
            $id = $this->input->get("id");
            $exec = $this->m_guru->lihatdatasatu($nip);
            if ($exec->num_rows()>0){
                $variabel['guru'] = $exec ->row_array();
                $exec2 = $this->m_guru->lihatdatasatuberkas($id);
                if ($exec2->num_rows()>0){

                    $variabel['data'] = $exec2->row_array();
                    $this->layout->render('back-end/datamaster/guru/v_guruberkas_edit',$variabel,'back-end/datamaster/guru/v_guruberkas_js');
                } else {
                    redirect(base_url("admin/datamaster/guruberkas?nip=$nip"));
                }
            } else {
                redirect(base_url("admin/datamaster/guru"));
            }
        }

    }

    // End CRUD Guru




    // CRUD Staff
    function staff()
    {
        $variabel['data'] = $this->m_staff->lihatdata();
        $this->layout->render('back-end/datamaster/staff/v_staff',$variabel,'back-end/datamaster/staff/v_staff_js');
    }

    function stafflihat()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_staff->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $this->layout->render('back-end/datamaster/staff/v_staff_lihat',$variabel,'back-end/datamaster/staff/v_staff_js');
        } else {
            redirect(base_url("admin/datamaster/staff"));
        }

    }

    function stafftambah()
    {
        if ($this->input->post()){

                $array=array(
                    'nip_staff'=> $this->input->post('nip_staff'),
                    'email_staff'=> $this->input->post('email_staff'),
                    'hp_staff'=> $this->input->post('hp_staff'),
                    'nama_lengkap'=>$this->input->post('nama_lengkap'),
                    'tempat_lahir'=>$this->input->post('tempat_lahir'),
                    'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                    'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                    'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                    'provinsi'=>$this->input->post('provinsi'),
                    'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                    'kecamatan'=>$this->input->post('kecamatan'),
                    'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                    'kode_pos'=>$this->input->post('kode_pos')
                    );
            if ($this->m_staff->cekdata($this->input->post('nip_staff'))==0) {
                $exec = $this->m_staff->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/stafftambah?msg=1"));
                else redirect(base_url("admin/datamaster/stafftambah?msg=0"));
            } else {
                $variabel['nip_staff'] =$this->input->post('nip_staff');
                $this->layout->render('back-end/datamaster/staff/v_staff_tambah',$variabel,'back-end/datamaster/staff/v_staff_js');
            }

        } else {
            $variabel ='';
            $this->layout->render('back-end/datamaster/staff/v_staff_tambah',$variabel,'back-end/datamaster/staff/v_staff_js');
        }
    }

    function staffedit()
    {
        if ($this->input->post()) {
            $array=array(
                'nip_staff'=> $this->input->post('nip_staff'),
                'email_staff'=> $this->input->post('email_staff'),
                'hp_staff'=> $this->input->post('hp_staff'),
                'nama_lengkap'=>$this->input->post('nama_lengkap'),
                'tempat_lahir'=>$this->input->post('tempat_lahir'),
                'tgl_lahir'=>tanggalawal($this->input->post('tgl_lahir')),
                'jenis_kelamin'=>$this->input->post('jenis_kelamin'),
                'alamat_lengkap'=>$this->input->post('alamat_lengkap'),
                'provinsi'=>$this->input->post('provinsi'),
                'kabupaten_kota'=>$this->input->post('kabupaten_kota'),
                'kecamatan'=>$this->input->post('kecamatan'),
                'desa_kelurahan'=>$this->input->post('desa_kelurahan'),
                'kode_pos'=>$this->input->post('kode_pos')
                );
            $nip2 = $this->input->post("nip_staff2");
            $nip = $this->input->post("nip_staff");
            if (($this->m_staff->cekdata($nip)>0) && ($nip2!=$nip)) {
                $variabel['nip_staff'] =$this->input->post('nip_staff');
                $variabel['nip_staff2'] =$this->input->post('nip_staff2');
                $variabel['data'] = $array;
                $this->layout->render('back-end/datamaster/staff/v_staff_edit',$variabel,'back-end/datamaster/staff/v_staff_js');
            } else {
                $exec = $this->m_staff->editdata($nip2,$array);
                if ($exec){
                  redirect(base_url("admin/datamaster/staffedit?nip=".$nip."&msg=1"));
                }
            }
      } else {
            $nip = $this->input->get("nip");
            $exec = $this->m_staff->lihatdatasatu($nip);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/datamaster/staff/v_staff_edit',$variabel,'back-end/datamaster/staff/v_staff_js');
            } else {
                redirect(base_url("admin/datamaster/staff"));
            }
      }

    }

    function staffhapus()
    {
       $nip = $this->input->get("nip");
       $exec = $this->m_staff->hapus($nip);
       redirect(base_url()."admin/datamaster/staff?msg=1");
    }

    function staffberkas()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_staff->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['staff'] = $exec->row_array();
            $variabel['data'] = $this->m_staff->lihatdataberkas($nip);
            $this->layout->render('back-end/datamaster/staff/v_staffberkas',$variabel,'back-end/datamaster/staff/v_staffberkas_js');
        } else {
            redirect(base_url("admin/datamaster/staff"));
        }

    }

    function stafftambahberkas()
    {
        $nip = $this->input->get("nip");
        $exec = $this->m_staff->lihatdatasatu($nip);
        if ($exec->num_rows()>0){
            $variabel['staff'] = $exec->row_array();
            if ($this->input->post()){
                $config['upload_path'] = './assets/berkas/berkasstaff';
                $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
                $this->load->library('upload', $config);
                $this->upload->do_upload("file_berkas");
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];

                $nip_staff = $this->input->post('nip_staff');
                $nama_berkas = $this->input->post('nama_berkas');
                $array=array(
                    'nip_staff'=>  $nip_staff,
                    'nama_berkas'=> $nama_berkas,
                    'file_berkas' => $file_berkas
                    );

                $exec = $this->m_staff->tambahdataberkas($array);
                if ($exec) redirect(base_url("admin/datamaster/stafftambahberkas?nip=".$nip_staff."&msg=1"));
                else redirect(base_url("admin/datamaster/staffberkastambah?nip=".$nip_staff."&msg=0"));
            } else {

                $this->layout->render('back-end/datamaster/staff/v_staffberkas_tambah',$variabel,'back-end/datamaster/staff/v_staffberkas_js');
            }
        } else {
            redirect(base_url("admin/datamaster/staff"));
        }
    }

    function staffhapusberkas()
    {
        $id_berkas = $this->input->get("id_berkas");
        $nip = $this->input->get("nip");

        $query2 = $this->m_staff->lihatdatasatuberkas($id_berkas);
        $row2 = $query2->row();
        $berkas1temp = $row2->file_berkas;
        $path1 ="./assets/berkas/berkasstaff/".$berkas1temp."";
        if(is_file($path1)) {
            unlink($path1);
        }

        $exec = $this->m_staff->hapusberkas($id_berkas);
        redirect(base_url()."admin/datamaster/staffberkas?msg=1&nip=".$nip."");
    }

    function staffeditberkas()
    {
        if ($this->input->post()) {
            $id_berkas = $this->input->post('id_berkas');
            $nama_berkas = $this->input->post('nama_berkas');
            $nip_staff = $this->input->post('nip_staff');
            $array=array(
                'nama_berkas'=> $nama_berkas
                );

            $config['upload_path'] = './assets/berkas/berkasstaff';
            $config['allowed_types'] = 'jpg|jpeg|JPG|JPEG|pdf';
            $this->load->library('upload', $config);
            if ( $this->upload->do_upload("file_berkas"))
            {
                $upload = $this->upload->data();
                $file_berkas = $upload["raw_name"].$upload["file_ext"];
                $array['file_berkas']=$file_berkas;

                $query2 = $this->m_staff->lihatdatasatuberkas($id_berkas);
                $row2 = $query2->row();
                $berkas1temp = $row2->file_berkas;
                $path1 ="./assets/berkas/berkasstaff/".$berkas1temp."";
                if(is_file($path1)) {
                    unlink($path1); //menghapus gambar di folder produk
                }
            }
            $exec = $this->m_staff->editdataaberkas($id_berkas,$array);
            if ($exec) redirect(base_url("admin/datamaster/staffeditberkas?id=".$id_berkas."&nip=".$nip_staff."&msg=1"));
            else redirect(base_url("admin/datamaster/staffeditberkas?id=".$id_berkas."&nip=".$nip_staff."&msg=0"));

        } else {
            $nip = $this->input->get("nip");
            $id = $this->input->get("id");
            $exec = $this->m_staff->lihatdatasatu($nip);
            if ($exec->num_rows()>0){
                $variabel['staff'] = $exec ->row_array();
                $exec2 = $this->m_staff->lihatdatasatuberkas($id);
                if ($exec2->num_rows()>0){

                    $variabel['data'] = $exec2->row_array();
                    $this->layout->render('back-end/datamaster/staff/v_staffberkas_edit',$variabel,'back-end/datamaster/staff/v_staffberkas_js');
                } else {
                    redirect(base_url("admin/datamaster/staffberkas?nip=$nip"));
                }
            } else {
                redirect(base_url("admin/datamaster/staff"));
            }
        }

    }

    // End CRUD Staff

    // CRUD tahun ajaran
    function tahunajar()
    {
        $variabel['data'] = $this->m_tahun_ajaran->lihatdata();
        $this->layout->render('back-end/datamaster/tahunajar/v_tahunajar',$variabel,'back-end/datamaster/tahunajar/v_tahunajar_js');
    }



    function tahunajartambah()
    {
        if ($this->input->post()){

                $array=array(

                    'tahun_ajaran'=> $this->input->post('tahun_ajaran'),
                    );
                $exec = $this->m_tahun_ajaran->tambahdata($array);
                if ($exec) redirect(base_url("admin/datamaster/tahunajartambah?msg=1"));
                else redirect(base_url("admin/datamaster/tahunajartambah?msg=0"));
            }

         else {
            $variabel ='';
            $this->layout->render('back-end/datamaster/tahunajar/v_tahunajar_tambah',$variabel,'back-end/datamaster/tahunajar/v_tahunajar_js');
        }
    }

    function tahunajaredit()
    {
        if ($this->input->post()) {
            $array=array(
              'id_tahun'=>$this->input->post('id_tahun'),
              'tahun_ajaran'=> $this->input->post('tahun_ajaran'),
                );
            $id_tahunlama = $this->input->post("id_tahunlama");
            $id_tahun = $this->input->post("id_tahun");
            if (($this->m_tahun_ajaran->cekdata($id_tahun)>0) && ($id_tahunlama!=$id_tahun)) {
                $variabel['id_tahun'] =$this->input->post('id_tahun');
                $variabel['id_tahunlama'] =$this->input->post('id_tahunlama');
                $variabel['data'] = $array;
                $this->layout->render('back-end/datamaster/tahunajar/v_tahunajar_edit',$variabel,'back-end/datamaster/tahunajar/v_tahunajar_js');
            } else {
                $exec = $this->m_tahun_ajaran->editdata($id_tahunlama,$array);
                if ($exec){
                  redirect(base_url("admin/datamaster/tahunajaredit?id_tahun=".$id_tahun."&msg=1"));
                }
            }
      } else {
            $id_tahun = $this->input->get("id_tahun");
            $exec = $this->m_tahun_ajaran->lihatdatasatu($id_tahun);
            if ($exec->num_rows()>0){
                $variabel['data'] = $exec ->row_array();
                $this->layout->render('back-end/datamaster/tahunajar/v_tahunajar_edit',$variabel,'back-end/datamaster/tahunajar/v_tahunajar_js');
            } else {
                redirect(base_url("admin/datamaster/tahunajar"));
            }
      }

    }

    function tahunajarhapus()
    {
       $id_tahun = $this->input->get("id_tahun");
       $exec = $this->m_tahun_ajaran->hapus($id_tahun);
       redirect(base_url()."admin/datamaster/tahunajar?msg=1");
    }

    // End CRUD tahunajar



   // CRUD provinsi
   function provinsi()
   {
       $variabel['data'] = $this->m_provinsi->lihatdata();
       $this->layout->render('back-end/datamaster/provinsi/v_provinsi',$variabel,'back-end/datamaster/provinsi/v_provinsi_js');
   }



   function provinsitambah()
   {
       if ($this->input->post()){

               $array=array(
                   'id_provinsi'=> $this->input->post('id_provinsi'),
                   'nama_provinsi'=> $this->input->post('nama_provinsi'),
                   );
           if ($this->m_provinsi->cekdata($this->input->post('id_provinsi'))==0) {
               $exec = $this->m_provinsi->tambahdata($array);
               if ($exec) redirect(base_url("admin/datamaster/provinsitambah?msg=1"));
               else redirect(base_url("admin/datamaster/provinsitambah?msg=0"));
           } else {
               $variabel['id_provinsi'] =$this->input->post('id_provinsi');
               $this->layout->render('back-end/datamaster/provinsi/v_provinsi_tambah',$variabel,'back-end/datamaster/provinsi/v_provinsi_js');
           }

       } else {
           $variabel ='';
           $this->layout->render('back-end/datamaster/provinsi/v_provinsi_tambah',$variabel,'back-end/datamaster/provinsi/v_provinsi_js');
       }
   }

   function provinsiedit()
   {
       if ($this->input->post()) {
           $array=array(
             'id_provinsi'=> $this->input->post('id_provinsi'),
             'nama_provinsi'=> $this->input->post('nama_provinsi'),
               );
           $id_provinsilama = $this->input->post("id_provinsilama");
           $id_provinsi = $this->input->post("id_provinsi");
           if (($this->m_provinsi->cekdata($id_provinsi)>0) && ($id_provinsilama!=$id_provinsi)) {
               $variabel['id_provinsi'] =$this->input->post('id_provinsi');
               $variabel['id_provinsilama'] =$this->input->post('id_provinsilama');
               $variabel['data'] = $array;
               $this->layout->render('back-end/datamaster/provinsi/v_provinsi_edit',$variabel,'back-end/datamaster/provinsi/v_provinsi_js');
           } else {
               $exec = $this->m_provinsi->editdata($id_provinsilama,$array);
               if ($exec){
                 redirect(base_url("admin/datamaster/provinsiedit?id_provinsi=".$id_provinsi."&msg=1"));
               }
           }
     } else {
           $id_provinsi = $this->input->get("id_provinsi");
           $exec = $this->m_provinsi->lihatdatasatu($id_provinsi);
           if ($exec->num_rows()>0){
               $variabel['data'] = $exec ->row_array();
               $this->layout->render('back-end/datamaster/provinsi/v_provinsi_edit',$variabel,'back-end/datamaster/provinsi/v_provinsi_js');
           } else {
               redirect(base_url("admin/datamaster/provinsi"));
           }
     }

   }

   function provinsihapus()
   {
      $id_provinsi = $this->input->get("id_provinsi");
      $exec = $this->m_provinsi->hapus($id_provinsi);
      redirect(base_url()."admin/datamaster/provinsi?msg=1");
   }

   // End CRUD Provinsi


// END Provinsi
// CRUD Kota dan Kabupaten


function kota_kab()
{
    $variabel['data'] = $this->m_kota_kab->lihatdata();
    $this->layout->render('back-end/datamaster/kota_kab/v_kota_kab',$variabel,'back-end/datamaster/kota_kab/v_kota_kab_js');
}



function kota_kabtambah()
{
    if ($this->input->post()){

            $array=array(
                'id_provinsi'=> $this->input->post('id_provinsi'),
                'nama_kota_kab'=> $this->input->post('nama_kota_kab'),
                );
            $exec = $this->m_kota_kab->tambahdata($array);
            if ($exec) redirect(base_url("admin/datamaster/kota_kabtambah?msg=1"));
            else redirect(base_url("admin/datamaster/kota_kabtambah?msg=0"));

    } else {

        $variabel['data'] =   $this->m_kota_kab->dataprovinsi();
        $this->layout->render('back-end/datamaster/kota_kab/v_kota_kab_tambah',$variabel,'back-end/datamaster/kota_kab/v_kota_kab_js');
    }
}

function kota_kabedit()
{
    if ($this->input->post()) {
        $array=array(
          'id_kota_kab'=> $this->input->post('id_kota_kab'),
          'nama_kota_kab'=> $this->input->post('nama_kota_kab'),
          'id_provinsi'=> $this->input->post('id_provinsi'),
            );
            $id_kota_kab = $this->input->post("id_kota_kab");
            $exec = $this->m_kota_kab->editdata($id_kota_kab,$array);
            if ($exec){
              redirect(base_url("admin/datamaster/kota_kabedit?id_kota_kab=".$id_kota_kab."&msg=1"));
            }

  } else {
        $id_kota_kab = $this->input->get("id_kota_kab");
        $exec = $this->m_kota_kab->lihatdatasatu($id_kota_kab);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $variabel['dataprovinsi'] = $this->m_kota_kab->dataprovinsi();
            $this->layout->render('back-end/datamaster/kota_kab/v_kota_kab_edit',$variabel,'back-end/datamaster/kota_kab/v_kota_kab_js');
        } else {
            redirect(base_url("admin/datamaster/kota_kab"));
        }
  }

}

function kota_kabhapus()
{
   $id_kota_kab = $this->input->get("id_kota_kab");
   $exec = $this->m_kota_kab->hapus($id_kota_kab);
   redirect(base_url()."admin/datamaster/kota_kab?msg=1");
}
// End CRUD Kota dan Kabupaten

// CRUD kecamatan
function kecamatan()
{
    $variabel['data'] = $this->m_kecamatan->lihatdata();
    $this->layout->render('back-end/datamaster/kecamatan/v_kecamatan',$variabel,'back-end/datamaster/kecamatan/v_kecamatan_js');
}

function datakotakab()
{
  $id=$this->input->post('id');
  $data=$this->m_kecamatan->datakota_kab($id);
  echo json_encode($data);
}

function kecamatantambah()
{
    if ($this->input->post()){

            $array=array(

                'id_kota_kab'=> $this->input->post('id_kota_kab'),
                'nama_kecamatan'=> $this->input->post('nama_kecamatan'),
                );
            $exec = $this->m_kecamatan->tambahdata($array);
            if ($exec) redirect(base_url("admin/datamaster/kecamatantambah?msg=1"));
            else redirect(base_url("admin/datamaster/kecamatantambah?msg=0"));

    } else {
        $variabel['data'] =   $this->m_kecamatan->dataprovinsi();
        $this->layout->render('back-end/datamaster/kecamatan/v_kecamatan_tambah',$variabel,'back-end/datamaster/kecamatan/v_kecamatan_js');
    }
}

function kecamatanedit()
{
    if ($this->input->post()) {
        $array=array(
          'id_kota_kab'=> $this->input->post('id_kota_kab'),
          'nama_kecamatan'=> $this->input->post('nama_kecamatan'),
            );
            $id_kecamatan = $this->input->post("id_kecamatan");
            $id_provinsi = $this->input->post("id_provinsi");
            $exec = $this->m_kecamatan->editdata($id_kecamatan,$array);
            if ($exec){
              redirect(base_url("admin/datamaster/kecamatanedit?id_kecamatan=".$id_kecamatan."&id_provinsi=".$id_provinsi."&msg=1"));
            }

  } else {
      $id_kecamatan = $this->input->get("id_kecamatan");
      $id_provinsi = $this->input->get("id_provinsi");
        $exec = $this->m_kecamatan->lihatdatasatu($id_kecamatan);
        if ($exec->num_rows()>0){
            $variabel['data'] = $exec ->row_array();
            $variabel['dataprovinsi'] = $this->m_kecamatan->dataprovinsi();
            $variabel['datakotakab']  = $this->m_kecamatan->datakotakab($id_provinsi);
            $this->layout->render('back-end/datamaster/kecamatan/v_kecamatan_edit',$variabel,'back-end/datamaster/kecamatan/v_kecamatan_js');
        } else {
            redirect(base_url("admin/datamaster/kecamatan"));
        }
  }

}

function kecamatanhapus()
{
   $id_kecamatan = $this->input->get("id_kecamatan");
   $exec = $this->m_kecamatan->hapus($id_kecamatan);
   redirect(base_url()."admin/datamaster/kecamatan?msg=1");
}
  // End CRUD Kecamatan

  // CRUD kel_desa
  function kel_desa()
  {
      $variabel['data'] = $this->m_kel_desa->lihatdata();
      $this->layout->render('back-end/datamaster/kel_desa/v_kel_desa',$variabel,'back-end/datamaster/kel_desa/v_kel_desa_js');
  }

  function datakecamatan()
  {
    $id=$this->input->post('id');
    $data=$this->m_kel_desa->datakecamatanajax($id);
    echo json_encode($data);
  }

  function kel_desatambah()
  {
      if ($this->input->post()){

              $array=array(

                  'id_kecamatan'=> $this->input->post('id_kecamatan'),
                  'nama_kel_desa'=> $this->input->post('nama_kel_desa'),
                  );
              $exec = $this->m_kel_desa->tambahdata($array);
              if ($exec) redirect(base_url("admin/datamaster/kel_desatambah?msg=1"));
              else redirect(base_url("admin/datamaster/kel_desatambah?msg=0"));

      } else {
          $variabel['data'] =   $this->m_kel_desa->dataprovinsi();
          $this->layout->render('back-end/datamaster/kel_desa/v_kel_desa_tambah',$variabel,'back-end/datamaster/kel_desa/v_kel_desa_js');
      }
  }

  function kel_desaedit()
  {
      if ($this->input->post()) {
          $array=array(
            'id_kecamatan'=> $this->input->post('id_kecamatan'),
            'nama_kel_desa'=> $this->input->post('nama_kel_desa'),
              );
              $id_kel_desa = $this->input->post("id_kel_desa");
              $id_provinsi = $this->input->post("id_provinsi");
              $id_kota_kab = $this->input->post("id_kota_kab");
              $exec = $this->m_kel_desa->editdata($id_kel_desa,$array);
              if ($exec){
                redirect(base_url("admin/datamaster/kel_desaedit?id_kel_desa=".$id_kel_desa."&id_provinsi=".$id_provinsi."&id_kota_kab=".$id_kota_kab."&msg=1"));
              }

    } else {
        $id_kel_desa  = $this->input->get("id_kel_desa");
        $id_provinsi = $this->input->get("id_provinsi");
        $id_kota_kab = $this->input->get("id_kota_kab");
          $exec = $this->m_kel_desa->lihatdatasatu($id_kel_desa);
          if ($exec->num_rows()>0){
              $variabel['data'] = $exec ->row_array();
              $variabel['dataprovinsi'] = $this->m_kel_desa->dataprovinsi();
              $variabel['datakotakab']  = $this->m_kel_desa->datakotakab($id_provinsi);
              $variabel['datakecamatan'] = $this->m_kel_desa->datakecamatan($id_kota_kab);
              $this->layout->render('back-end/datamaster/kel_desa/v_kel_desa_edit',$variabel,'back-end/datamaster/kel_desa/v_kel_desa_js');
          } else {
              redirect(base_url("admin/datamaster/kel_desa"));
          }
    }

  }

  function kel_desahapus()
  {
     $id_kel_desa = $this->input->get("id_kel_desa");
     $exec = $this->m_kel_desa->hapus($id_kel_desa);
     redirect(base_url()."admin/datamaster/kel_desa?msg=1");
  }
    // End CRUD Kecamatan


   // CRUD Pendidikan
   function pendidikan()
   {
       $variabel['data'] = $this->m_pendidikan->lihatdata();
       $this->layout->render('back-end/datamaster/pendidikan/v_pendidikan',$variabel,'back-end/datamaster/pendidikan/v_pendidikan_js');
   }

   function pendidikantambah()
   {
       if ($this->input->post()){

               $array=array(
                   'id_pendidikan'=> $this->input->post('id_pendidikan'),
                   'nama_pendidikan'=> $this->input->post('nama_pendidikan'),
                   );
           if ($this->m_pendidikan->cekdata($this->input->post('id_pendidikan'))==0) {
               $exec = $this->m_pendidikan->tambahdata($array);
               if ($exec) redirect(base_url("admin/datamaster/pendidikantambah?msg=1"));
               else redirect(base_url("admin/datamaster/pendidikantambah?msg=0"));
           } else {
               $variabel['id_pendidikan'] =$this->input->post('id_pendidikan');
               $this->layout->render('back-end/datamaster/pendidikan/v_pendidikan_tambah',$variabel,'back-end/datamaster/pendidikan/v_pendidikan_js');
           }

       } else {
           $variabel ='';
           $this->layout->render('back-end/datamaster/pendidikan/v_pendidikan_tambah',$variabel,'back-end/datamaster/pendidikan/v_pendidikan_js');
       }
   }

   function pendidikanedit()
   {
       if ($this->input->post()) {
           $array=array(
             'id_pendidikan'=> $this->input->post('id_pendidikan'),
             'nama_pendidikan'=> $this->input->post('nama_pendidikan'),
               );
           $id_pendidikanlama = $this->input->post("id_pendidikanlama");
           $id_pendidikan = $this->input->post("id_pendidikan");
           if (($this->m_pendidikan->cekdata($id_pendidikan)>0) && ($id_pendidikanlama!=$id_pendidikan)) {
               $variabel['id_pendidikan'] =$this->input->post('id_pendidikan');
               $variabel['id_pendidikanlama'] =$this->input->post('id_pendidikanlama');
               $variabel['data'] = $array;
               $this->layout->render('back-end/datamaster/pendidikan/v_pendidikan_edit',$variabel,'back-end/datamaster/pendidikan/v_pendidikan_js');
           } else {
               $exec = $this->m_pendidikan->editdata($id_pendidikanlama,$array);
               if ($exec){
                 redirect(base_url("admin/datamaster/pendidikanedit?id_pendidikan=".$id_pendidikan."&msg=1"));
               }
           }
     } else {
           $id_pendidikan = $this->input->get("id_pendidikan");
           $exec = $this->m_pendidikan->lihatdatasatu($id_pendidikan);
           if ($exec->num_rows()>0){
               $variabel['data'] = $exec ->row_array();
               $this->layout->render('back-end/datamaster/pendidikan/v_pendidikan_edit',$variabel,'back-end/datamaster/pendidikan/v_pendidikan_js');
           } else {
               redirect(base_url("admin/datamaster/pendidikan"));
           }
     }

   }

   function pendidikanhapus()
   {
      $id_pendidikan = $this->input->get("id_pendidikan");
      $exec = $this->m_pendidikan->hapus($id_pendidikan);
      redirect(base_url()."admin/datamaster/pendidikan?msg=1");
   }
   // End CRUD Pendidikan


   // CRUD Pekerjaan
   function pekerjaan()
   {
       $variabel['data'] = $this->m_pekerjaan->lihatdata();
       $this->layout->render('back-end/datamaster/pekerjaan/v_pekerjaan',$variabel,'back-end/datamaster/pekerjaan/v_pekerjaan_js');
   }

   function pekerjaantambah()
   {
       if ($this->input->post()){

               $array=array(
                   'id_pekerjaan'=> $this->input->post('id_pekerjaan'),
                   'nama_pekerjaan'=> $this->input->post('nama_pekerjaan'),
                   );
           if ($this->m_pekerjaan->cekdata($this->input->post('id_pekerjaan'))==0) {
               $exec = $this->m_pekerjaan->tambahdata($array);
               if ($exec) redirect(base_url("admin/datamaster/pekerjaantambah?msg=1"));
               else redirect(base_url("admin/datamaster/pekerjaantambah?msg=0"));
           } else {
               $variabel['id_pekerjaan'] =$this->input->post('id_pekerjaan');
               $this->layout->render('back-end/datamaster/pekerjaan/v_pekerjaan_tambah',$variabel,'back-end/datamaster/pekerjaan/v_pekerjaan_js');
           }

       } else {
           $variabel ='';
           $this->layout->render('back-end/datamaster/pekerjaan/v_pekerjaan_tambah',$variabel,'back-end/datamaster/pekerjaan/v_pekerjaan_js');
       }
   }

   function pekerjaanedit()
   {
       if ($this->input->post()) {
           $array=array(
             'id_pekerjaan'=> $this->input->post('id_pekerjaan'),
             'nama_pekerjaan'=> $this->input->post('nama_pekerjaan'),
               );
           $id_pekerjaanlama = $this->input->post("id_pekerjaanlama");
           $id_pekerjaan = $this->input->post("id_pekerjaan");
           if (($this->m_pekerjaan->cekdata($id_pekerjaan)>0) && ($id_pekerjaanlama!=$id_pekerjaan)) {
               $variabel['id_pekerjaan'] =$this->input->post('id_pekerjaan');
               $variabel['id_pekerjaanlama'] =$this->input->post('id_pekerjaanlama');
               $variabel['data'] = $array;
               $this->layout->render('back-end/datamaster/pekerjaan/v_pekerjaan_edit',$variabel,'back-end/datamaster/pekerjaan/v_pekerjaan_js');
           } else {
               $exec = $this->m_pekerjaan->editdata($id_pekerjaanlama,$array);
               if ($exec){
                 redirect(base_url("admin/datamaster/pekerjaanedit?id_pekerjaan=".$id_pekerjaan."&msg=1"));
               }
           }
     } else {
           $id_pekerjaan = $this->input->get("id_pekerjaan");
           $exec = $this->m_pekerjaan->lihatdatasatu($id_pekerjaan);
           if ($exec->num_rows()>0){
               $variabel['data'] = $exec ->row_array();
               $this->layout->render('back-end/datamaster/pekerjaan/v_pekerjaan_edit',$variabel,'back-end/datamaster/pekerjaan/v_pekerjaan_js');
           } else {
               redirect(base_url("admin/datamaster/pekerjaan"));
           }
     }

   }

   function pekerjaanhapus()
   {
      $id_pekerjaan = $this->input->get("id_pekerjaan");
      $exec = $this->m_pekerjaan->hapus($id_pekerjaan);
      redirect(base_url()."admin/datamaster/pekerjaan?msg=1");
   }
   // End CRUD Pekerjaan



   // CRUD Alat Transportasi
   function alat_transportasi()
   {
       $variabel['data'] = $this->m_alat_transportasi->lihatdata();
       $this->layout->render('back-end/datamaster/alat_transportasi/v_alat_transportasi',$variabel,'back-end/datamaster/alat_transportasi/v_alat_transportasi_js');
   }

   function alat_transportasitambah()
   {
       if ($this->input->post()){

               $array=array(
                   'id_alat_transportasi'=> $this->input->post('id_alat_transportasi'),
                   'nama_alat_transportasi'=> $this->input->post('nama_alat_transportasi'),
                   );
           if ($this->m_alat_transportasi->cekdata($this->input->post('id_alat_transportasi'))==0) {
               $exec = $this->m_alat_transportasi->tambahdata($array);
               if ($exec) redirect(base_url("admin/datamaster/alat_transportasitambah?msg=1"));
               else redirect(base_url("admin/datamaster/alat_transportasitambah?msg=0"));
           } else {
               $variabel['id_alat_transportasi'] =$this->input->post('id_alat_transportasi');
               $this->layout->render('back-end/datamaster/alat_transportasi/v_alat_transportasi_tambah',$variabel,'back-end/datamaster/alat_transportasi/v_alat_transportasi_js');
           }

       } else {
           $variabel ='';
           $this->layout->render('back-end/datamaster/alat_transportasi/v_alat_transportasi_tambah',$variabel,'back-end/datamaster/alat_transportasi/v_alat_transportasi_js');
       }
   }

   function alat_transportasiedit()
   {
       if ($this->input->post()) {
           $array=array(
             'id_alat_transportasi'=> $this->input->post('id_alat_transportasi'),
             'nama_alat_transportasi'=> $this->input->post('nama_alat_transportasi'),
               );
           $id_alat_transportasilama = $this->input->post("id_alat_transportasilama");
           $id_alat_transportasi = $this->input->post("id_alat_transportasi");
           if (($this->m_alat_transportasi->cekdata($id_alat_transportasi)>0) && ($id_alat_transportasilama!=$id_alat_transportasi)) {
               $variabel['id_alat_transportasi'] =$this->input->post('id_alat_transportasi');
               $variabel['id_alat_transportasilama'] =$this->input->post('id_alat_transportasilama');
               $variabel['data'] = $array;
               $this->layout->render('back-end/datamaster/alat_transportasi/v_alat_transportasi_edit',$variabel,'back-end/datamaster/alat_transportasi/v_alat_transportasi_js');
           } else {
               $exec = $this->m_alat_transportasi->editdata($id_alat_transportasilama,$array);
               if ($exec){
                 redirect(base_url("admin/datamaster/alat_transportasiedit?id_alat_transportasi=".$id_alat_transportasi."&msg=1"));
               }
           }
     } else {
           $id_alat_transportasi = $this->input->get("id_alat_transportasi");
           $exec = $this->m_alat_transportasi->lihatdatasatu($id_alat_transportasi);
           if ($exec->num_rows()>0){
               $variabel['data'] = $exec ->row_array();
               $this->layout->render('back-end/datamaster/alat_transportasi/v_alat_transportasi_edit',$variabel,'back-end/datamaster/alat_transportasi/v_alat_transportasi_js');
           } else {
               redirect(base_url("admin/datamaster/alat_transportasi"));
           }
     }

   }

   function alat_transportasihapus()
   {
      $id_alat_transportasi = $this->input->get("id_alat_transportasi");
      $exec = $this->m_alat_transportasi->hapus($id_alat_transportasi);
      redirect(base_url()."admin/datamaster/alat_transportasi?msg=1");
   }
   // End CRUD Alat Transportasi

///////////////////////////////////////////memulai presensi////////////////////////////////////////////////
   function datakelasbelajar()
   {
     $variabel='';
      $this->layout->render('back-end/presensi/presensi_kelas/v_presensi_kelas',$variabel,'back-end/presensi/presensi_kelas/v_preskelas_js');
   }

   function aturkelasbelajar(){
     $variabel='';
     $this->layout->render('back-end/presensi/presensi_kelas/v_presensi_atur',$variabel,'back-end/presensi/presensi_kelas/v_preskelas_js');
   }
/////////////////////////////////akhir presensi/////////////////////////////////////////////////////


////////////////////////////////////////////////// pembayaran SPP ////////////////////////////////////////////////////
  function databayarinfaq(){
    if($this->input->post()){
      $tahun = $this->input->post('tahun');
      $bulan = $this->input->post('bulan');
      $variabel['bulan'] = $bulan;
      $variabel['tahun'] = $tahun;
      $variabel['data'] = $this->m_infaq->lihatdata($tahun,$bulan);
      $this->layout->render('back-end/infaq/v_data_infaq',$variabel,'back-end/infaq/v_infaq_js');}
      else {
        $tahun = date('Y');
        $bulan = date('m');
        $variabel['bulan'] = $bulan;
        $variabel['tahun'] = $tahun;
        $variabel['data'] = $this->m_infaq->lihatdata($tahun,$bulan);
        $this->layout->render('back-end/infaq/v_data_infaq',$variabel,'back-end/infaq/v_infaq_js');
      }
    }

  function detilinfaq(){
    $nis = $this->input->get('nis');
    $variabel['nama_santri'] = $this->m_infaq->lihatsantrisatu($nis);
    $variabel['data'] = $this->m_infaq->detilinfaq($nis);
    $this->layout->render('back-end/infaq/v_detil_infaq',$variabel,'back-end/infaq/v_infaq_js');
  }

  function bayarinfaq(){
    if($this->input->post()){
      $array = array(
        'nis_santri' => $this->input->post('id_santri'),
        'tanggal_bayar' => date('Y-m-d'),
        'spp_bulan' => $this->input->post('bulan'),
        'spp_tahun' => $this->input->post('tahun'),
        'status_bayar' => 'lunas',
        'petugas' => $this->session->userdata('nama_akun')
      );
      $exec = $this->m_infaq->tambahdata($array);
      if($exec){
        redirect(base_url("admin/datamaster/bayarinfaq?msg=1"));
      } else{
        redirect(base_url("admin/datamaster/bayarinfaq?msg=0"));
      }
    }else{
      $variabel['daftarsantri'] = $this->m_infaq->datasantri();
      $this->layout->render('back-end/infaq/v_bayar_infaq',$variabel,'back-end/infaq/v_infaq_js');
    }

  }

  function hapusinfaq(){
    $id_infaq = $this->input->get("id_infaq");
    $exec = $this->m_infaq->hapus($id_infaq);
    redirect(base_url()."admin/datamaster/databayarinfaq?msg=1");
  }

  //////////////////////////////////////////akhir pembayaran spp/////////////////////////////////////////
}
